// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns OK when the treasury API process is running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Service liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handlers.livenessResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Exposes Prometheus metrics for scraping.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "Prometheus metrics payload",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Validates connectivity to Postgres, Redis, NATS, and storage backends.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handlers.readinessResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handlers.readinessResponse"
                        }
                    }
                }
            }
        },
        "/{tenantID}/ledger/chart-of-accounts": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "Returns the ledger chart of accounts for the requesting tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ledger"
                ],
                "summary": "List chart of accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant identifier",
                        "name": "tenantID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handlers.chartOfAccountsResponse"
                        }
                    }
                }
            }
        },
        "/{tenantID}/payments/intents": {
            "get": {
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "description": "Returns the payment intents that have been created for the tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "List payment intents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant identifier",
                        "name": "tenantID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_handlers.paymentIntentsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_http_handlers.chartOfAccountsResponse": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_http_handlers.ledgerAccount"
                    }
                }
            }
        },
        "internal_http_handlers.ledgerAccount": {
            "type": "object",
            "properties": {
                "allowPostings": {
                    "type": "boolean",
                    "example": true
                },
                "balance": {
                    "type": "string",
                    "example": "0"
                },
                "code": {
                    "type": "string",
                    "example": "1000"
                },
                "currency": {
                    "type": "string",
                    "example": "KES"
                },
                "name": {
                    "type": "string",
                    "example": "Platform Cash"
                },
                "tenant": {
                    "type": "string",
                    "example": "tenant-123"
                },
                "type": {
                    "type": "string",
                    "example": "asset"
                }
            }
        },
        "internal_http_handlers.livenessResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "treasury-app"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_http_handlers.paymentIntent": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "0.00"
                },
                "currency": {
                    "type": "string",
                    "example": "KES"
                },
                "id": {
                    "type": "string",
                    "example": "pi_123"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "internal_http_handlers.paymentIntentsResponse": {
            "type": "object",
            "properties": {
                "intents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_http_handlers.paymentIntent"
                    }
                }
            }
        },
        "internal_http_handlers.readinessResponse": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        }
    },
    "securityDefinitions": {
        "bearerAuth": {
            "description": "JWT token from auth-service. Format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Treasury Service API",
	Description:      "HTTP API for the BengoBox treasury service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
