// Code generated by ent, DO NOT EDIT.

package treasurypermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/treasury-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLTE(FieldID, id))
}

// PermissionCode applies equality check predicate on the "permission_code" field. It's identical to PermissionCodeEQ.
func PermissionCode(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldPermissionCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldName, v))
}

// Module applies equality check predicate on the "module" field. It's identical to ModuleEQ.
func Module(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldModule, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldAction, v))
}

// Resource applies equality check predicate on the "resource" field. It's identical to ResourceEQ.
func Resource(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldResource, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldCreatedAt, v))
}

// PermissionCodeEQ applies the EQ predicate on the "permission_code" field.
func PermissionCodeEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldPermissionCode, v))
}

// PermissionCodeNEQ applies the NEQ predicate on the "permission_code" field.
func PermissionCodeNEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNEQ(FieldPermissionCode, v))
}

// PermissionCodeIn applies the In predicate on the "permission_code" field.
func PermissionCodeIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIn(FieldPermissionCode, vs...))
}

// PermissionCodeNotIn applies the NotIn predicate on the "permission_code" field.
func PermissionCodeNotIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotIn(FieldPermissionCode, vs...))
}

// PermissionCodeGT applies the GT predicate on the "permission_code" field.
func PermissionCodeGT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGT(FieldPermissionCode, v))
}

// PermissionCodeGTE applies the GTE predicate on the "permission_code" field.
func PermissionCodeGTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGTE(FieldPermissionCode, v))
}

// PermissionCodeLT applies the LT predicate on the "permission_code" field.
func PermissionCodeLT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLT(FieldPermissionCode, v))
}

// PermissionCodeLTE applies the LTE predicate on the "permission_code" field.
func PermissionCodeLTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLTE(FieldPermissionCode, v))
}

// PermissionCodeContains applies the Contains predicate on the "permission_code" field.
func PermissionCodeContains(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContains(FieldPermissionCode, v))
}

// PermissionCodeHasPrefix applies the HasPrefix predicate on the "permission_code" field.
func PermissionCodeHasPrefix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasPrefix(FieldPermissionCode, v))
}

// PermissionCodeHasSuffix applies the HasSuffix predicate on the "permission_code" field.
func PermissionCodeHasSuffix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasSuffix(FieldPermissionCode, v))
}

// PermissionCodeEqualFold applies the EqualFold predicate on the "permission_code" field.
func PermissionCodeEqualFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEqualFold(FieldPermissionCode, v))
}

// PermissionCodeContainsFold applies the ContainsFold predicate on the "permission_code" field.
func PermissionCodeContainsFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContainsFold(FieldPermissionCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContainsFold(FieldName, v))
}

// ModuleEQ applies the EQ predicate on the "module" field.
func ModuleEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldModule, v))
}

// ModuleNEQ applies the NEQ predicate on the "module" field.
func ModuleNEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNEQ(FieldModule, v))
}

// ModuleIn applies the In predicate on the "module" field.
func ModuleIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIn(FieldModule, vs...))
}

// ModuleNotIn applies the NotIn predicate on the "module" field.
func ModuleNotIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotIn(FieldModule, vs...))
}

// ModuleGT applies the GT predicate on the "module" field.
func ModuleGT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGT(FieldModule, v))
}

// ModuleGTE applies the GTE predicate on the "module" field.
func ModuleGTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGTE(FieldModule, v))
}

// ModuleLT applies the LT predicate on the "module" field.
func ModuleLT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLT(FieldModule, v))
}

// ModuleLTE applies the LTE predicate on the "module" field.
func ModuleLTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLTE(FieldModule, v))
}

// ModuleContains applies the Contains predicate on the "module" field.
func ModuleContains(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContains(FieldModule, v))
}

// ModuleHasPrefix applies the HasPrefix predicate on the "module" field.
func ModuleHasPrefix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasPrefix(FieldModule, v))
}

// ModuleHasSuffix applies the HasSuffix predicate on the "module" field.
func ModuleHasSuffix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasSuffix(FieldModule, v))
}

// ModuleEqualFold applies the EqualFold predicate on the "module" field.
func ModuleEqualFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEqualFold(FieldModule, v))
}

// ModuleContainsFold applies the ContainsFold predicate on the "module" field.
func ModuleContainsFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContainsFold(FieldModule, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContainsFold(FieldAction, v))
}

// ResourceEQ applies the EQ predicate on the "resource" field.
func ResourceEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldResource, v))
}

// ResourceNEQ applies the NEQ predicate on the "resource" field.
func ResourceNEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNEQ(FieldResource, v))
}

// ResourceIn applies the In predicate on the "resource" field.
func ResourceIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIn(FieldResource, vs...))
}

// ResourceNotIn applies the NotIn predicate on the "resource" field.
func ResourceNotIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotIn(FieldResource, vs...))
}

// ResourceGT applies the GT predicate on the "resource" field.
func ResourceGT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGT(FieldResource, v))
}

// ResourceGTE applies the GTE predicate on the "resource" field.
func ResourceGTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGTE(FieldResource, v))
}

// ResourceLT applies the LT predicate on the "resource" field.
func ResourceLT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLT(FieldResource, v))
}

// ResourceLTE applies the LTE predicate on the "resource" field.
func ResourceLTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLTE(FieldResource, v))
}

// ResourceContains applies the Contains predicate on the "resource" field.
func ResourceContains(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContains(FieldResource, v))
}

// ResourceHasPrefix applies the HasPrefix predicate on the "resource" field.
func ResourceHasPrefix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasPrefix(FieldResource, v))
}

// ResourceHasSuffix applies the HasSuffix predicate on the "resource" field.
func ResourceHasSuffix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasSuffix(FieldResource, v))
}

// ResourceIsNil applies the IsNil predicate on the "resource" field.
func ResourceIsNil() predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIsNull(FieldResource))
}

// ResourceNotNil applies the NotNil predicate on the "resource" field.
func ResourceNotNil() predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotNull(FieldResource))
}

// ResourceEqualFold applies the EqualFold predicate on the "resource" field.
func ResourceEqualFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEqualFold(FieldResource, v))
}

// ResourceContainsFold applies the ContainsFold predicate on the "resource" field.
func ResourceContainsFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContainsFold(FieldResource, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRoles applies the HasEdge predicate on the "roles" edge.
func HasRoles() predicate.TreasuryPermission {
	return predicate.TreasuryPermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, RolesTable, RolesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRolesWith applies the HasEdge predicate on the "roles" edge with a given conditions (other predicates).
func HasRolesWith(preds ...predicate.TreasuryRole) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(func(s *sql.Selector) {
		step := newRolesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRolePermissions applies the HasEdge predicate on the "role_permissions" edge.
func HasRolePermissions() predicate.TreasuryPermission {
	return predicate.TreasuryPermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RolePermissionsTable, RolePermissionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRolePermissionsWith applies the HasEdge predicate on the "role_permissions" edge with a given conditions (other predicates).
func HasRolePermissionsWith(preds ...predicate.RolePermission) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(func(s *sql.Selector) {
		step := newRolePermissionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TreasuryPermission) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TreasuryPermission) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TreasuryPermission) predicate.TreasuryPermission {
	return predicate.TreasuryPermission(sql.NotPredicates(p))
}
