// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/treasury-api/internal/ent/chartofaccount"
	"github.com/bengobox/treasury-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ChartOfAccountQuery is the builder for querying ChartOfAccount entities.
type ChartOfAccountQuery struct {
	config
	ctx          *QueryContext
	order        []chartofaccount.OrderOption
	inters       []Interceptor
	predicates   []predicate.ChartOfAccount
	withParent   *ChartOfAccountQuery
	withChildren *ChartOfAccountQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChartOfAccountQuery builder.
func (_q *ChartOfAccountQuery) Where(ps ...predicate.ChartOfAccount) *ChartOfAccountQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChartOfAccountQuery) Limit(limit int) *ChartOfAccountQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChartOfAccountQuery) Offset(offset int) *ChartOfAccountQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChartOfAccountQuery) Unique(unique bool) *ChartOfAccountQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChartOfAccountQuery) Order(o ...chartofaccount.OrderOption) *ChartOfAccountQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryParent chains the current query on the "parent" edge.
func (_q *ChartOfAccountQuery) QueryParent() *ChartOfAccountQuery {
	query := (&ChartOfAccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chartofaccount.Table, chartofaccount.FieldID, selector),
			sqlgraph.To(chartofaccount.Table, chartofaccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chartofaccount.ParentTable, chartofaccount.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (_q *ChartOfAccountQuery) QueryChildren() *ChartOfAccountQuery {
	query := (&ChartOfAccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chartofaccount.Table, chartofaccount.FieldID, selector),
			sqlgraph.To(chartofaccount.Table, chartofaccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, chartofaccount.ChildrenTable, chartofaccount.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChartOfAccount entity from the query.
// Returns a *NotFoundError when no ChartOfAccount was found.
func (_q *ChartOfAccountQuery) First(ctx context.Context) (*ChartOfAccount, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chartofaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChartOfAccountQuery) FirstX(ctx context.Context) *ChartOfAccount {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChartOfAccount ID from the query.
// Returns a *NotFoundError when no ChartOfAccount ID was found.
func (_q *ChartOfAccountQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chartofaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChartOfAccountQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChartOfAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChartOfAccount entity is found.
// Returns a *NotFoundError when no ChartOfAccount entities are found.
func (_q *ChartOfAccountQuery) Only(ctx context.Context) (*ChartOfAccount, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chartofaccount.Label}
	default:
		return nil, &NotSingularError{chartofaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChartOfAccountQuery) OnlyX(ctx context.Context) *ChartOfAccount {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChartOfAccount ID in the query.
// Returns a *NotSingularError when more than one ChartOfAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChartOfAccountQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chartofaccount.Label}
	default:
		err = &NotSingularError{chartofaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChartOfAccountQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChartOfAccounts.
func (_q *ChartOfAccountQuery) All(ctx context.Context) ([]*ChartOfAccount, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChartOfAccount, *ChartOfAccountQuery]()
	return withInterceptors[[]*ChartOfAccount](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChartOfAccountQuery) AllX(ctx context.Context) []*ChartOfAccount {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChartOfAccount IDs.
func (_q *ChartOfAccountQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(chartofaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChartOfAccountQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChartOfAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChartOfAccountQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChartOfAccountQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChartOfAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChartOfAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChartOfAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChartOfAccountQuery) Clone() *ChartOfAccountQuery {
	if _q == nil {
		return nil
	}
	return &ChartOfAccountQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]chartofaccount.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.ChartOfAccount{}, _q.predicates...),
		withParent:   _q.withParent.Clone(),
		withChildren: _q.withChildren.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChartOfAccountQuery) WithParent(opts ...func(*ChartOfAccountQuery)) *ChartOfAccountQuery {
	query := (&ChartOfAccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParent = query
	return _q
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChartOfAccountQuery) WithChildren(opts ...func(*ChartOfAccountQuery)) *ChartOfAccountQuery {
	query := (&ChartOfAccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChildren = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChartOfAccount.Query().
//		GroupBy(chartofaccount.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChartOfAccountQuery) GroupBy(field string, fields ...string) *ChartOfAccountGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChartOfAccountGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chartofaccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//	}
//
//	client.ChartOfAccount.Query().
//		Select(chartofaccount.FieldTenantID).
//		Scan(ctx, &v)
func (_q *ChartOfAccountQuery) Select(fields ...string) *ChartOfAccountSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChartOfAccountSelect{ChartOfAccountQuery: _q}
	sbuild.label = chartofaccount.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChartOfAccountSelect configured with the given aggregations.
func (_q *ChartOfAccountQuery) Aggregate(fns ...AggregateFunc) *ChartOfAccountSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChartOfAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chartofaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChartOfAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChartOfAccount, error) {
	var (
		nodes       = []*ChartOfAccount{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withParent != nil,
			_q.withChildren != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChartOfAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChartOfAccount{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withParent; query != nil {
		if err := _q.loadParent(ctx, query, nodes, nil,
			func(n *ChartOfAccount, e *ChartOfAccount) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChildren; query != nil {
		if err := _q.loadChildren(ctx, query, nodes,
			func(n *ChartOfAccount) { n.Edges.Children = []*ChartOfAccount{} },
			func(n *ChartOfAccount, e *ChartOfAccount) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChartOfAccountQuery) loadParent(ctx context.Context, query *ChartOfAccountQuery, nodes []*ChartOfAccount, init func(*ChartOfAccount), assign func(*ChartOfAccount, *ChartOfAccount)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ChartOfAccount)
	for i := range nodes {
		fk := nodes[i].ParentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chartofaccount.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChartOfAccountQuery) loadChildren(ctx context.Context, query *ChartOfAccountQuery, nodes []*ChartOfAccount, init func(*ChartOfAccount), assign func(*ChartOfAccount, *ChartOfAccount)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*ChartOfAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(chartofaccount.FieldParentID)
	}
	query.Where(predicate.ChartOfAccount(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(chartofaccount.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ChartOfAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChartOfAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chartofaccount.Table, chartofaccount.Columns, sqlgraph.NewFieldSpec(chartofaccount.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chartofaccount.FieldID)
		for i := range fields {
			if fields[i] != chartofaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withParent != nil {
			_spec.Node.AddColumnOnce(chartofaccount.FieldParentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChartOfAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chartofaccount.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chartofaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChartOfAccountGroupBy is the group-by builder for ChartOfAccount entities.
type ChartOfAccountGroupBy struct {
	selector
	build *ChartOfAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChartOfAccountGroupBy) Aggregate(fns ...AggregateFunc) *ChartOfAccountGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChartOfAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChartOfAccountQuery, *ChartOfAccountGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChartOfAccountGroupBy) sqlScan(ctx context.Context, root *ChartOfAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChartOfAccountSelect is the builder for selecting fields of ChartOfAccount entities.
type ChartOfAccountSelect struct {
	*ChartOfAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChartOfAccountSelect) Aggregate(fns ...AggregateFunc) *ChartOfAccountSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChartOfAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChartOfAccountQuery, *ChartOfAccountSelect](ctx, _s.ChartOfAccountQuery, _s, _s.inters, v)
}

func (_s *ChartOfAccountSelect) sqlScan(ctx context.Context, root *ChartOfAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
