// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/treasury-api/internal/ent/invoice"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// InvoiceCreate is the builder for creating a Invoice entity.
type InvoiceCreate struct {
	config
	mutation *InvoiceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *InvoiceCreate) SetTenantID(v uuid.UUID) *InvoiceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_c *InvoiceCreate) SetInvoiceNumber(v string) *InvoiceCreate {
	_c.mutation.SetInvoiceNumber(v)
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *InvoiceCreate) SetCustomerID(v uuid.UUID) *InvoiceCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableCustomerID(v *uuid.UUID) *InvoiceCreate {
	if v != nil {
		_c.SetCustomerID(*v)
	}
	return _c
}

// SetInvoiceType sets the "invoice_type" field.
func (_c *InvoiceCreate) SetInvoiceType(v string) *InvoiceCreate {
	_c.mutation.SetInvoiceType(v)
	return _c
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableInvoiceType(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetInvoiceType(*v)
	}
	return _c
}

// SetInvoiceDate sets the "invoice_date" field.
func (_c *InvoiceCreate) SetInvoiceDate(v time.Time) *InvoiceCreate {
	_c.mutation.SetInvoiceDate(v)
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *InvoiceCreate) SetDueDate(v time.Time) *InvoiceCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetSubtotal sets the "subtotal" field.
func (_c *InvoiceCreate) SetSubtotal(v decimal.Decimal) *InvoiceCreate {
	_c.mutation.SetSubtotal(v)
	return _c
}

// SetTaxAmount sets the "tax_amount" field.
func (_c *InvoiceCreate) SetTaxAmount(v decimal.Decimal) *InvoiceCreate {
	_c.mutation.SetTaxAmount(v)
	return _c
}

// SetNillableTaxAmount sets the "tax_amount" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableTaxAmount(v *decimal.Decimal) *InvoiceCreate {
	if v != nil {
		_c.SetTaxAmount(*v)
	}
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *InvoiceCreate) SetTotalAmount(v decimal.Decimal) *InvoiceCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *InvoiceCreate) SetCurrency(v string) *InvoiceCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableCurrency(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceCreate) SetStatus(v string) *InvoiceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableStatus(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPaymentStatus sets the "payment_status" field.
func (_c *InvoiceCreate) SetPaymentStatus(v string) *InvoiceCreate {
	_c.mutation.SetPaymentStatus(v)
	return _c
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillablePaymentStatus(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetPaymentStatus(*v)
	}
	return _c
}

// SetReferenceID sets the "reference_id" field.
func (_c *InvoiceCreate) SetReferenceID(v uuid.UUID) *InvoiceCreate {
	_c.mutation.SetReferenceID(v)
	return _c
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableReferenceID(v *uuid.UUID) *InvoiceCreate {
	if v != nil {
		_c.SetReferenceID(*v)
	}
	return _c
}

// SetReferenceType sets the "reference_type" field.
func (_c *InvoiceCreate) SetReferenceType(v string) *InvoiceCreate {
	_c.mutation.SetReferenceType(v)
	return _c
}

// SetNillableReferenceType sets the "reference_type" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableReferenceType(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetReferenceType(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *InvoiceCreate) SetMetadata(v map[string]interface{}) *InvoiceCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceCreate) SetCreatedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableCreatedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceCreate) SetUpdatedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InvoiceCreate) SetID(v uuid.UUID) *InvoiceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableID(v *uuid.UUID) *InvoiceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the InvoiceMutation object of the builder.
func (_c *InvoiceCreate) Mutation() *InvoiceMutation {
	return _c.mutation
}

// Save creates the Invoice in the database.
func (_c *InvoiceCreate) Save(ctx context.Context) (*Invoice, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceCreate) SaveX(ctx context.Context) *Invoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceCreate) defaults() {
	if _, ok := _c.mutation.InvoiceType(); !ok {
		v := invoice.DefaultInvoiceType
		_c.mutation.SetInvoiceType(v)
	}
	if _, ok := _c.mutation.TaxAmount(); !ok {
		v := invoice.DefaultTaxAmount
		_c.mutation.SetTaxAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := invoice.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoice.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PaymentStatus(); !ok {
		v := invoice.DefaultPaymentStatus
		_c.mutation.SetPaymentStatus(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := invoice.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := invoice.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Invoice.tenant_id"`)}
	}
	if _, ok := _c.mutation.InvoiceNumber(); !ok {
		return &ValidationError{Name: "invoice_number", err: errors.New(`ent: missing required field "Invoice.invoice_number"`)}
	}
	if v, ok := _c.mutation.InvoiceNumber(); ok {
		if err := invoice.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "Invoice.invoice_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InvoiceType(); !ok {
		return &ValidationError{Name: "invoice_type", err: errors.New(`ent: missing required field "Invoice.invoice_type"`)}
	}
	if _, ok := _c.mutation.InvoiceDate(); !ok {
		return &ValidationError{Name: "invoice_date", err: errors.New(`ent: missing required field "Invoice.invoice_date"`)}
	}
	if _, ok := _c.mutation.DueDate(); !ok {
		return &ValidationError{Name: "due_date", err: errors.New(`ent: missing required field "Invoice.due_date"`)}
	}
	if _, ok := _c.mutation.Subtotal(); !ok {
		return &ValidationError{Name: "subtotal", err: errors.New(`ent: missing required field "Invoice.subtotal"`)}
	}
	if _, ok := _c.mutation.TaxAmount(); !ok {
		return &ValidationError{Name: "tax_amount", err: errors.New(`ent: missing required field "Invoice.tax_amount"`)}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "Invoice.total_amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Invoice.currency"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Invoice.status"`)}
	}
	if _, ok := _c.mutation.PaymentStatus(); !ok {
		return &ValidationError{Name: "payment_status", err: errors.New(`ent: missing required field "Invoice.payment_status"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Invoice.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Invoice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Invoice.updated_at"`)}
	}
	return nil
}

func (_c *InvoiceCreate) sqlSave(ctx context.Context) (*Invoice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceCreate) createSpec() (*Invoice, *sqlgraph.CreateSpec) {
	var (
		_node = &Invoice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoice.Table, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(invoice.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoice.FieldInvoiceNumber, field.TypeString, value)
		_node.InvoiceNumber = value
	}
	if value, ok := _c.mutation.CustomerID(); ok {
		_spec.SetField(invoice.FieldCustomerID, field.TypeUUID, value)
		_node.CustomerID = value
	}
	if value, ok := _c.mutation.InvoiceType(); ok {
		_spec.SetField(invoice.FieldInvoiceType, field.TypeString, value)
		_node.InvoiceType = value
	}
	if value, ok := _c.mutation.InvoiceDate(); ok {
		_spec.SetField(invoice.FieldInvoiceDate, field.TypeTime, value)
		_node.InvoiceDate = value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(invoice.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if value, ok := _c.mutation.Subtotal(); ok {
		_spec.SetField(invoice.FieldSubtotal, field.TypeFloat64, value)
		_node.Subtotal = value
	}
	if value, ok := _c.mutation.TaxAmount(); ok {
		_spec.SetField(invoice.FieldTaxAmount, field.TypeFloat64, value)
		_node.TaxAmount = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(invoice.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(invoice.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PaymentStatus(); ok {
		_spec.SetField(invoice.FieldPaymentStatus, field.TypeString, value)
		_node.PaymentStatus = value
	}
	if value, ok := _c.mutation.ReferenceID(); ok {
		_spec.SetField(invoice.FieldReferenceID, field.TypeUUID, value)
		_node.ReferenceID = value
	}
	if value, ok := _c.mutation.ReferenceType(); ok {
		_spec.SetField(invoice.FieldReferenceType, field.TypeString, value)
		_node.ReferenceType = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(invoice.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invoice.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceUpsertOne {
	_c.conflict = opts
	return &InvoiceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceCreate) OnConflictColumns(columns ...string) *InvoiceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceUpsertOne is the builder for "upsert"-ing
	//  one Invoice node.
	InvoiceUpsertOne struct {
		create *InvoiceCreate
	}

	// InvoiceUpsert is the "OnConflict" setter.
	InvoiceUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *InvoiceUpsert) SetTenantID(v uuid.UUID) *InvoiceUpsert {
	u.Set(invoice.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateTenantID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldTenantID)
	return u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceUpsert) SetInvoiceNumber(v string) *InvoiceUpsert {
	u.Set(invoice.FieldInvoiceNumber, v)
	return u
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateInvoiceNumber() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldInvoiceNumber)
	return u
}

// SetCustomerID sets the "customer_id" field.
func (u *InvoiceUpsert) SetCustomerID(v uuid.UUID) *InvoiceUpsert {
	u.Set(invoice.FieldCustomerID, v)
	return u
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateCustomerID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldCustomerID)
	return u
}

// ClearCustomerID clears the value of the "customer_id" field.
func (u *InvoiceUpsert) ClearCustomerID() *InvoiceUpsert {
	u.SetNull(invoice.FieldCustomerID)
	return u
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceUpsert) SetInvoiceType(v string) *InvoiceUpsert {
	u.Set(invoice.FieldInvoiceType, v)
	return u
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateInvoiceType() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldInvoiceType)
	return u
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceUpsert) SetInvoiceDate(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldInvoiceDate, v)
	return u
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateInvoiceDate() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldInvoiceDate)
	return u
}

// SetDueDate sets the "due_date" field.
func (u *InvoiceUpsert) SetDueDate(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldDueDate, v)
	return u
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateDueDate() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldDueDate)
	return u
}

// SetSubtotal sets the "subtotal" field.
func (u *InvoiceUpsert) SetSubtotal(v decimal.Decimal) *InvoiceUpsert {
	u.Set(invoice.FieldSubtotal, v)
	return u
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateSubtotal() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldSubtotal)
	return u
}

// AddSubtotal adds v to the "subtotal" field.
func (u *InvoiceUpsert) AddSubtotal(v decimal.Decimal) *InvoiceUpsert {
	u.Add(invoice.FieldSubtotal, v)
	return u
}

// SetTaxAmount sets the "tax_amount" field.
func (u *InvoiceUpsert) SetTaxAmount(v decimal.Decimal) *InvoiceUpsert {
	u.Set(invoice.FieldTaxAmount, v)
	return u
}

// UpdateTaxAmount sets the "tax_amount" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateTaxAmount() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldTaxAmount)
	return u
}

// AddTaxAmount adds v to the "tax_amount" field.
func (u *InvoiceUpsert) AddTaxAmount(v decimal.Decimal) *InvoiceUpsert {
	u.Add(invoice.FieldTaxAmount, v)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceUpsert) SetTotalAmount(v decimal.Decimal) *InvoiceUpsert {
	u.Set(invoice.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateTotalAmount() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceUpsert) AddTotalAmount(v decimal.Decimal) *InvoiceUpsert {
	u.Add(invoice.FieldTotalAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsert) SetCurrency(v string) *InvoiceUpsert {
	u.Set(invoice.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateCurrency() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldCurrency)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsert) SetStatus(v string) *InvoiceUpsert {
	u.Set(invoice.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateStatus() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldStatus)
	return u
}

// SetPaymentStatus sets the "payment_status" field.
func (u *InvoiceUpsert) SetPaymentStatus(v string) *InvoiceUpsert {
	u.Set(invoice.FieldPaymentStatus, v)
	return u
}

// UpdatePaymentStatus sets the "payment_status" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdatePaymentStatus() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldPaymentStatus)
	return u
}

// SetReferenceID sets the "reference_id" field.
func (u *InvoiceUpsert) SetReferenceID(v uuid.UUID) *InvoiceUpsert {
	u.Set(invoice.FieldReferenceID, v)
	return u
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateReferenceID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldReferenceID)
	return u
}

// ClearReferenceID clears the value of the "reference_id" field.
func (u *InvoiceUpsert) ClearReferenceID() *InvoiceUpsert {
	u.SetNull(invoice.FieldReferenceID)
	return u
}

// SetReferenceType sets the "reference_type" field.
func (u *InvoiceUpsert) SetReferenceType(v string) *InvoiceUpsert {
	u.Set(invoice.FieldReferenceType, v)
	return u
}

// UpdateReferenceType sets the "reference_type" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateReferenceType() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldReferenceType)
	return u
}

// ClearReferenceType clears the value of the "reference_type" field.
func (u *InvoiceUpsert) ClearReferenceType() *InvoiceUpsert {
	u.SetNull(invoice.FieldReferenceType)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *InvoiceUpsert) SetMetadata(v map[string]interface{}) *InvoiceUpsert {
	u.Set(invoice.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateMetadata() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsert) SetUpdatedAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateUpdatedAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(invoice.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InvoiceUpsertOne) UpdateNewValues() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(invoice.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoice.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceUpsertOne) Ignore() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceUpsertOne) DoNothing() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceCreate.OnConflict
// documentation for more info.
func (u *InvoiceUpsertOne) Update(set func(*InvoiceUpsert)) *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *InvoiceUpsertOne) SetTenantID(v uuid.UUID) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateTenantID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTenantID()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceUpsertOne) SetInvoiceNumber(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateInvoiceNumber() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// SetCustomerID sets the "customer_id" field.
func (u *InvoiceUpsertOne) SetCustomerID(v uuid.UUID) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCustomerID(v)
	})
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateCustomerID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCustomerID()
	})
}

// ClearCustomerID clears the value of the "customer_id" field.
func (u *InvoiceUpsertOne) ClearCustomerID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearCustomerID()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceUpsertOne) SetInvoiceType(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateInvoiceType() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceUpsertOne) SetInvoiceDate(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceDate(v)
	})
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateInvoiceDate() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceDate()
	})
}

// SetDueDate sets the "due_date" field.
func (u *InvoiceUpsertOne) SetDueDate(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetDueDate(v)
	})
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateDueDate() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateDueDate()
	})
}

// SetSubtotal sets the "subtotal" field.
func (u *InvoiceUpsertOne) SetSubtotal(v decimal.Decimal) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetSubtotal(v)
	})
}

// AddSubtotal adds v to the "subtotal" field.
func (u *InvoiceUpsertOne) AddSubtotal(v decimal.Decimal) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddSubtotal(v)
	})
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateSubtotal() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateSubtotal()
	})
}

// SetTaxAmount sets the "tax_amount" field.
func (u *InvoiceUpsertOne) SetTaxAmount(v decimal.Decimal) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTaxAmount(v)
	})
}

// AddTaxAmount adds v to the "tax_amount" field.
func (u *InvoiceUpsertOne) AddTaxAmount(v decimal.Decimal) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddTaxAmount(v)
	})
}

// UpdateTaxAmount sets the "tax_amount" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateTaxAmount() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTaxAmount()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceUpsertOne) SetTotalAmount(v decimal.Decimal) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceUpsertOne) AddTotalAmount(v decimal.Decimal) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateTotalAmount() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsertOne) SetCurrency(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateCurrency() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsertOne) SetStatus(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateStatus() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentStatus sets the "payment_status" field.
func (u *InvoiceUpsertOne) SetPaymentStatus(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetPaymentStatus(v)
	})
}

// UpdatePaymentStatus sets the "payment_status" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdatePaymentStatus() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdatePaymentStatus()
	})
}

// SetReferenceID sets the "reference_id" field.
func (u *InvoiceUpsertOne) SetReferenceID(v uuid.UUID) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetReferenceID(v)
	})
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateReferenceID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateReferenceID()
	})
}

// ClearReferenceID clears the value of the "reference_id" field.
func (u *InvoiceUpsertOne) ClearReferenceID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearReferenceID()
	})
}

// SetReferenceType sets the "reference_type" field.
func (u *InvoiceUpsertOne) SetReferenceType(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetReferenceType(v)
	})
}

// UpdateReferenceType sets the "reference_type" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateReferenceType() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateReferenceType()
	})
}

// ClearReferenceType clears the value of the "reference_type" field.
func (u *InvoiceUpsertOne) ClearReferenceType() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearReferenceType()
	})
}

// SetMetadata sets the "metadata" field.
func (u *InvoiceUpsertOne) SetMetadata(v map[string]interface{}) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateMetadata() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsertOne) SetUpdatedAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateUpdatedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InvoiceUpsertOne.ID is not supported by MySQL driver. Use InvoiceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceCreateBulk is the builder for creating many Invoice entities in bulk.
type InvoiceCreateBulk struct {
	config
	err      error
	builders []*InvoiceCreate
	conflict []sql.ConflictOption
}

// Save creates the Invoice entities in the database.
func (_c *InvoiceCreateBulk) Save(ctx context.Context) ([]*Invoice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invoice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceCreateBulk) SaveX(ctx context.Context) []*Invoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invoice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceUpsertBulk {
	_c.conflict = opts
	return &InvoiceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceCreateBulk) OnConflictColumns(columns ...string) *InvoiceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceUpsertBulk{
		create: _c,
	}
}

// InvoiceUpsertBulk is the builder for "upsert"-ing
// a bulk of Invoice nodes.
type InvoiceUpsertBulk struct {
	create *InvoiceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(invoice.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InvoiceUpsertBulk) UpdateNewValues() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(invoice.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoice.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceUpsertBulk) Ignore() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceUpsertBulk) DoNothing() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceUpsertBulk) Update(set func(*InvoiceUpsert)) *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *InvoiceUpsertBulk) SetTenantID(v uuid.UUID) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateTenantID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTenantID()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceUpsertBulk) SetInvoiceNumber(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateInvoiceNumber() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// SetCustomerID sets the "customer_id" field.
func (u *InvoiceUpsertBulk) SetCustomerID(v uuid.UUID) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCustomerID(v)
	})
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateCustomerID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCustomerID()
	})
}

// ClearCustomerID clears the value of the "customer_id" field.
func (u *InvoiceUpsertBulk) ClearCustomerID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearCustomerID()
	})
}

// SetInvoiceType sets the "invoice_type" field.
func (u *InvoiceUpsertBulk) SetInvoiceType(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceType(v)
	})
}

// UpdateInvoiceType sets the "invoice_type" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateInvoiceType() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceType()
	})
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceUpsertBulk) SetInvoiceDate(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetInvoiceDate(v)
	})
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateInvoiceDate() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateInvoiceDate()
	})
}

// SetDueDate sets the "due_date" field.
func (u *InvoiceUpsertBulk) SetDueDate(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetDueDate(v)
	})
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateDueDate() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateDueDate()
	})
}

// SetSubtotal sets the "subtotal" field.
func (u *InvoiceUpsertBulk) SetSubtotal(v decimal.Decimal) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetSubtotal(v)
	})
}

// AddSubtotal adds v to the "subtotal" field.
func (u *InvoiceUpsertBulk) AddSubtotal(v decimal.Decimal) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddSubtotal(v)
	})
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateSubtotal() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateSubtotal()
	})
}

// SetTaxAmount sets the "tax_amount" field.
func (u *InvoiceUpsertBulk) SetTaxAmount(v decimal.Decimal) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTaxAmount(v)
	})
}

// AddTaxAmount adds v to the "tax_amount" field.
func (u *InvoiceUpsertBulk) AddTaxAmount(v decimal.Decimal) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddTaxAmount(v)
	})
}

// UpdateTaxAmount sets the "tax_amount" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateTaxAmount() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTaxAmount()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceUpsertBulk) SetTotalAmount(v decimal.Decimal) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *InvoiceUpsertBulk) AddTotalAmount(v decimal.Decimal) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateTotalAmount() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsertBulk) SetCurrency(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateCurrency() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsertBulk) SetStatus(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateStatus() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentStatus sets the "payment_status" field.
func (u *InvoiceUpsertBulk) SetPaymentStatus(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetPaymentStatus(v)
	})
}

// UpdatePaymentStatus sets the "payment_status" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdatePaymentStatus() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdatePaymentStatus()
	})
}

// SetReferenceID sets the "reference_id" field.
func (u *InvoiceUpsertBulk) SetReferenceID(v uuid.UUID) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetReferenceID(v)
	})
}

// UpdateReferenceID sets the "reference_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateReferenceID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateReferenceID()
	})
}

// ClearReferenceID clears the value of the "reference_id" field.
func (u *InvoiceUpsertBulk) ClearReferenceID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearReferenceID()
	})
}

// SetReferenceType sets the "reference_type" field.
func (u *InvoiceUpsertBulk) SetReferenceType(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetReferenceType(v)
	})
}

// UpdateReferenceType sets the "reference_type" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateReferenceType() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateReferenceType()
	})
}

// ClearReferenceType clears the value of the "reference_type" field.
func (u *InvoiceUpsertBulk) ClearReferenceType() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearReferenceType()
	})
}

// SetMetadata sets the "metadata" field.
func (u *InvoiceUpsertBulk) SetMetadata(v map[string]interface{}) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateMetadata() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateUpdatedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
