// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/treasury-api/internal/ent/chartofaccount"
	"github.com/bengobox/treasury-api/internal/ent/ledgertransaction"
	"github.com/bengobox/treasury-api/internal/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LedgerTransactionUpdate is the builder for updating LedgerTransaction entities.
type LedgerTransactionUpdate struct {
	config
	hooks    []Hook
	mutation *LedgerTransactionMutation
}

// Where appends a list predicates to the LedgerTransactionUpdate builder.
func (_u *LedgerTransactionUpdate) Where(ps ...predicate.LedgerTransaction) *LedgerTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *LedgerTransactionUpdate) SetTenantID(v uuid.UUID) *LedgerTransactionUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableTenantID(v *uuid.UUID) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *LedgerTransactionUpdate) SetAccountID(v uuid.UUID) *LedgerTransactionUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableAccountID(v *uuid.UUID) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetJournalEntryID sets the "journal_entry_id" field.
func (_u *LedgerTransactionUpdate) SetJournalEntryID(v uuid.UUID) *LedgerTransactionUpdate {
	_u.mutation.SetJournalEntryID(v)
	return _u
}

// SetNillableJournalEntryID sets the "journal_entry_id" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableJournalEntryID(v *uuid.UUID) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetJournalEntryID(*v)
	}
	return _u
}

// ClearJournalEntryID clears the value of the "journal_entry_id" field.
func (_u *LedgerTransactionUpdate) ClearJournalEntryID() *LedgerTransactionUpdate {
	_u.mutation.ClearJournalEntryID()
	return _u
}

// SetDebitAmount sets the "debit_amount" field.
func (_u *LedgerTransactionUpdate) SetDebitAmount(v decimal.Decimal) *LedgerTransactionUpdate {
	_u.mutation.ResetDebitAmount()
	_u.mutation.SetDebitAmount(v)
	return _u
}

// SetNillableDebitAmount sets the "debit_amount" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableDebitAmount(v *decimal.Decimal) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetDebitAmount(*v)
	}
	return _u
}

// AddDebitAmount adds value to the "debit_amount" field.
func (_u *LedgerTransactionUpdate) AddDebitAmount(v decimal.Decimal) *LedgerTransactionUpdate {
	_u.mutation.AddDebitAmount(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *LedgerTransactionUpdate) SetCreditAmount(v decimal.Decimal) *LedgerTransactionUpdate {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableCreditAmount(v *decimal.Decimal) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *LedgerTransactionUpdate) AddCreditAmount(v decimal.Decimal) *LedgerTransactionUpdate {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *LedgerTransactionUpdate) SetCurrency(v string) *LedgerTransactionUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableCurrency(v *string) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetExchangeRate sets the "exchange_rate" field.
func (_u *LedgerTransactionUpdate) SetExchangeRate(v decimal.Decimal) *LedgerTransactionUpdate {
	_u.mutation.ResetExchangeRate()
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableExchangeRate(v *decimal.Decimal) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// AddExchangeRate adds value to the "exchange_rate" field.
func (_u *LedgerTransactionUpdate) AddExchangeRate(v decimal.Decimal) *LedgerTransactionUpdate {
	_u.mutation.AddExchangeRate(v)
	return _u
}

// SetReferenceType sets the "reference_type" field.
func (_u *LedgerTransactionUpdate) SetReferenceType(v string) *LedgerTransactionUpdate {
	_u.mutation.SetReferenceType(v)
	return _u
}

// SetNillableReferenceType sets the "reference_type" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableReferenceType(v *string) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetReferenceType(*v)
	}
	return _u
}

// ClearReferenceType clears the value of the "reference_type" field.
func (_u *LedgerTransactionUpdate) ClearReferenceType() *LedgerTransactionUpdate {
	_u.mutation.ClearReferenceType()
	return _u
}

// SetReferenceID sets the "reference_id" field.
func (_u *LedgerTransactionUpdate) SetReferenceID(v uuid.UUID) *LedgerTransactionUpdate {
	_u.mutation.SetReferenceID(v)
	return _u
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableReferenceID(v *uuid.UUID) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetReferenceID(*v)
	}
	return _u
}

// ClearReferenceID clears the value of the "reference_id" field.
func (_u *LedgerTransactionUpdate) ClearReferenceID() *LedgerTransactionUpdate {
	_u.mutation.ClearReferenceID()
	return _u
}

// SetTransactionDate sets the "transaction_date" field.
func (_u *LedgerTransactionUpdate) SetTransactionDate(v time.Time) *LedgerTransactionUpdate {
	_u.mutation.SetTransactionDate(v)
	return _u
}

// SetNillableTransactionDate sets the "transaction_date" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableTransactionDate(v *time.Time) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetTransactionDate(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *LedgerTransactionUpdate) SetDescription(v string) *LedgerTransactionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LedgerTransactionUpdate) SetNillableDescription(v *string) *LedgerTransactionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LedgerTransactionUpdate) ClearDescription() *LedgerTransactionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LedgerTransactionUpdate) SetMetadata(v map[string]interface{}) *LedgerTransactionUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetAccount sets the "account" edge to the ChartOfAccount entity.
func (_u *LedgerTransactionUpdate) SetAccount(v *ChartOfAccount) *LedgerTransactionUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the LedgerTransactionMutation object of the builder.
func (_u *LedgerTransactionUpdate) Mutation() *LedgerTransactionMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the ChartOfAccount entity.
func (_u *LedgerTransactionUpdate) ClearAccount() *LedgerTransactionUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LedgerTransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LedgerTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerTransactionUpdate) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LedgerTransaction.account"`)
	}
	return nil
}

func (_u *LedgerTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledgertransaction.Table, ledgertransaction.Columns, sqlgraph.NewFieldSpec(ledgertransaction.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(ledgertransaction.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.JournalEntryID(); ok {
		_spec.SetField(ledgertransaction.FieldJournalEntryID, field.TypeUUID, value)
	}
	if _u.mutation.JournalEntryIDCleared() {
		_spec.ClearField(ledgertransaction.FieldJournalEntryID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DebitAmount(); ok {
		_spec.SetField(ledgertransaction.FieldDebitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDebitAmount(); ok {
		_spec.AddField(ledgertransaction.FieldDebitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(ledgertransaction.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(ledgertransaction.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(ledgertransaction.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(ledgertransaction.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExchangeRate(); ok {
		_spec.AddField(ledgertransaction.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReferenceType(); ok {
		_spec.SetField(ledgertransaction.FieldReferenceType, field.TypeString, value)
	}
	if _u.mutation.ReferenceTypeCleared() {
		_spec.ClearField(ledgertransaction.FieldReferenceType, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceID(); ok {
		_spec.SetField(ledgertransaction.FieldReferenceID, field.TypeUUID, value)
	}
	if _u.mutation.ReferenceIDCleared() {
		_spec.ClearField(ledgertransaction.FieldReferenceID, field.TypeUUID)
	}
	if value, ok := _u.mutation.TransactionDate(); ok {
		_spec.SetField(ledgertransaction.FieldTransactionDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ledgertransaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ledgertransaction.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(ledgertransaction.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledgertransaction.AccountTable,
			Columns: []string{ledgertransaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chartofaccount.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledgertransaction.AccountTable,
			Columns: []string{ledgertransaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chartofaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgertransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LedgerTransactionUpdateOne is the builder for updating a single LedgerTransaction entity.
type LedgerTransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LedgerTransactionMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *LedgerTransactionUpdateOne) SetTenantID(v uuid.UUID) *LedgerTransactionUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableTenantID(v *uuid.UUID) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *LedgerTransactionUpdateOne) SetAccountID(v uuid.UUID) *LedgerTransactionUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableAccountID(v *uuid.UUID) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetJournalEntryID sets the "journal_entry_id" field.
func (_u *LedgerTransactionUpdateOne) SetJournalEntryID(v uuid.UUID) *LedgerTransactionUpdateOne {
	_u.mutation.SetJournalEntryID(v)
	return _u
}

// SetNillableJournalEntryID sets the "journal_entry_id" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableJournalEntryID(v *uuid.UUID) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetJournalEntryID(*v)
	}
	return _u
}

// ClearJournalEntryID clears the value of the "journal_entry_id" field.
func (_u *LedgerTransactionUpdateOne) ClearJournalEntryID() *LedgerTransactionUpdateOne {
	_u.mutation.ClearJournalEntryID()
	return _u
}

// SetDebitAmount sets the "debit_amount" field.
func (_u *LedgerTransactionUpdateOne) SetDebitAmount(v decimal.Decimal) *LedgerTransactionUpdateOne {
	_u.mutation.ResetDebitAmount()
	_u.mutation.SetDebitAmount(v)
	return _u
}

// SetNillableDebitAmount sets the "debit_amount" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableDebitAmount(v *decimal.Decimal) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetDebitAmount(*v)
	}
	return _u
}

// AddDebitAmount adds value to the "debit_amount" field.
func (_u *LedgerTransactionUpdateOne) AddDebitAmount(v decimal.Decimal) *LedgerTransactionUpdateOne {
	_u.mutation.AddDebitAmount(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *LedgerTransactionUpdateOne) SetCreditAmount(v decimal.Decimal) *LedgerTransactionUpdateOne {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableCreditAmount(v *decimal.Decimal) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *LedgerTransactionUpdateOne) AddCreditAmount(v decimal.Decimal) *LedgerTransactionUpdateOne {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *LedgerTransactionUpdateOne) SetCurrency(v string) *LedgerTransactionUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableCurrency(v *string) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetExchangeRate sets the "exchange_rate" field.
func (_u *LedgerTransactionUpdateOne) SetExchangeRate(v decimal.Decimal) *LedgerTransactionUpdateOne {
	_u.mutation.ResetExchangeRate()
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableExchangeRate(v *decimal.Decimal) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// AddExchangeRate adds value to the "exchange_rate" field.
func (_u *LedgerTransactionUpdateOne) AddExchangeRate(v decimal.Decimal) *LedgerTransactionUpdateOne {
	_u.mutation.AddExchangeRate(v)
	return _u
}

// SetReferenceType sets the "reference_type" field.
func (_u *LedgerTransactionUpdateOne) SetReferenceType(v string) *LedgerTransactionUpdateOne {
	_u.mutation.SetReferenceType(v)
	return _u
}

// SetNillableReferenceType sets the "reference_type" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableReferenceType(v *string) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetReferenceType(*v)
	}
	return _u
}

// ClearReferenceType clears the value of the "reference_type" field.
func (_u *LedgerTransactionUpdateOne) ClearReferenceType() *LedgerTransactionUpdateOne {
	_u.mutation.ClearReferenceType()
	return _u
}

// SetReferenceID sets the "reference_id" field.
func (_u *LedgerTransactionUpdateOne) SetReferenceID(v uuid.UUID) *LedgerTransactionUpdateOne {
	_u.mutation.SetReferenceID(v)
	return _u
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableReferenceID(v *uuid.UUID) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetReferenceID(*v)
	}
	return _u
}

// ClearReferenceID clears the value of the "reference_id" field.
func (_u *LedgerTransactionUpdateOne) ClearReferenceID() *LedgerTransactionUpdateOne {
	_u.mutation.ClearReferenceID()
	return _u
}

// SetTransactionDate sets the "transaction_date" field.
func (_u *LedgerTransactionUpdateOne) SetTransactionDate(v time.Time) *LedgerTransactionUpdateOne {
	_u.mutation.SetTransactionDate(v)
	return _u
}

// SetNillableTransactionDate sets the "transaction_date" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableTransactionDate(v *time.Time) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetTransactionDate(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *LedgerTransactionUpdateOne) SetDescription(v string) *LedgerTransactionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LedgerTransactionUpdateOne) SetNillableDescription(v *string) *LedgerTransactionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LedgerTransactionUpdateOne) ClearDescription() *LedgerTransactionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LedgerTransactionUpdateOne) SetMetadata(v map[string]interface{}) *LedgerTransactionUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetAccount sets the "account" edge to the ChartOfAccount entity.
func (_u *LedgerTransactionUpdateOne) SetAccount(v *ChartOfAccount) *LedgerTransactionUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the LedgerTransactionMutation object of the builder.
func (_u *LedgerTransactionUpdateOne) Mutation() *LedgerTransactionMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the ChartOfAccount entity.
func (_u *LedgerTransactionUpdateOne) ClearAccount() *LedgerTransactionUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the LedgerTransactionUpdate builder.
func (_u *LedgerTransactionUpdateOne) Where(ps ...predicate.LedgerTransaction) *LedgerTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LedgerTransactionUpdateOne) Select(field string, fields ...string) *LedgerTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LedgerTransaction entity.
func (_u *LedgerTransactionUpdateOne) Save(ctx context.Context) (*LedgerTransaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerTransactionUpdateOne) SaveX(ctx context.Context) *LedgerTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LedgerTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerTransactionUpdateOne) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LedgerTransaction.account"`)
	}
	return nil
}

func (_u *LedgerTransactionUpdateOne) sqlSave(ctx context.Context) (_node *LedgerTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledgertransaction.Table, ledgertransaction.Columns, sqlgraph.NewFieldSpec(ledgertransaction.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LedgerTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledgertransaction.FieldID)
		for _, f := range fields {
			if !ledgertransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ledgertransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(ledgertransaction.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.JournalEntryID(); ok {
		_spec.SetField(ledgertransaction.FieldJournalEntryID, field.TypeUUID, value)
	}
	if _u.mutation.JournalEntryIDCleared() {
		_spec.ClearField(ledgertransaction.FieldJournalEntryID, field.TypeUUID)
	}
	if value, ok := _u.mutation.DebitAmount(); ok {
		_spec.SetField(ledgertransaction.FieldDebitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDebitAmount(); ok {
		_spec.AddField(ledgertransaction.FieldDebitAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(ledgertransaction.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(ledgertransaction.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(ledgertransaction.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(ledgertransaction.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedExchangeRate(); ok {
		_spec.AddField(ledgertransaction.FieldExchangeRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReferenceType(); ok {
		_spec.SetField(ledgertransaction.FieldReferenceType, field.TypeString, value)
	}
	if _u.mutation.ReferenceTypeCleared() {
		_spec.ClearField(ledgertransaction.FieldReferenceType, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceID(); ok {
		_spec.SetField(ledgertransaction.FieldReferenceID, field.TypeUUID, value)
	}
	if _u.mutation.ReferenceIDCleared() {
		_spec.ClearField(ledgertransaction.FieldReferenceID, field.TypeUUID)
	}
	if value, ok := _u.mutation.TransactionDate(); ok {
		_spec.SetField(ledgertransaction.FieldTransactionDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ledgertransaction.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ledgertransaction.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(ledgertransaction.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledgertransaction.AccountTable,
			Columns: []string{ledgertransaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chartofaccount.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ledgertransaction.AccountTable,
			Columns: []string{ledgertransaction.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chartofaccount.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LedgerTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgertransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
