// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/treasury-api/internal/ent/chartofaccount"
	"github.com/bengobox/treasury-api/internal/ent/ledgertransaction"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LedgerTransaction is the model entity for the LedgerTransaction schema.
type LedgerTransaction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Tenant identifier
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Account identifier
	AccountID uuid.UUID `json:"account_id,omitempty"`
	// Journal entry identifier
	JournalEntryID uuid.UUID `json:"journal_entry_id,omitempty"`
	// Debit amount
	DebitAmount decimal.Decimal `json:"debit_amount,omitempty"`
	// Credit amount
	CreditAmount decimal.Decimal `json:"credit_amount,omitempty"`
	// ISO currency code
	Currency string `json:"currency,omitempty"`
	// FX rate for multi-currency
	ExchangeRate decimal.Decimal `json:"exchange_rate,omitempty"`
	// Reference entity type (invoice, bill, payment)
	ReferenceType string `json:"reference_type,omitempty"`
	// Reference entity ID
	ReferenceID uuid.UUID `json:"reference_id,omitempty"`
	// Transaction date
	TransactionDate time.Time `json:"transaction_date,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LedgerTransactionQuery when eager-loading is set.
	Edges        LedgerTransactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LedgerTransactionEdges holds the relations/edges for other nodes in the graph.
type LedgerTransactionEdges struct {
	// Account holds the value of the account edge.
	Account *ChartOfAccount `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LedgerTransactionEdges) AccountOrErr() (*ChartOfAccount, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chartofaccount.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LedgerTransaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ledgertransaction.FieldMetadata:
			values[i] = new([]byte)
		case ledgertransaction.FieldDebitAmount, ledgertransaction.FieldCreditAmount, ledgertransaction.FieldExchangeRate:
			values[i] = new(decimal.Decimal)
		case ledgertransaction.FieldCurrency, ledgertransaction.FieldReferenceType, ledgertransaction.FieldDescription:
			values[i] = new(sql.NullString)
		case ledgertransaction.FieldTransactionDate, ledgertransaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case ledgertransaction.FieldID, ledgertransaction.FieldTenantID, ledgertransaction.FieldAccountID, ledgertransaction.FieldJournalEntryID, ledgertransaction.FieldReferenceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LedgerTransaction fields.
func (_m *LedgerTransaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ledgertransaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ledgertransaction.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case ledgertransaction.FieldAccountID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value != nil {
				_m.AccountID = *value
			}
		case ledgertransaction.FieldJournalEntryID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field journal_entry_id", values[i])
			} else if value != nil {
				_m.JournalEntryID = *value
			}
		case ledgertransaction.FieldDebitAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field debit_amount", values[i])
			} else if value != nil {
				_m.DebitAmount = *value
			}
		case ledgertransaction.FieldCreditAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field credit_amount", values[i])
			} else if value != nil {
				_m.CreditAmount = *value
			}
		case ledgertransaction.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case ledgertransaction.FieldExchangeRate:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_rate", values[i])
			} else if value != nil {
				_m.ExchangeRate = *value
			}
		case ledgertransaction.FieldReferenceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_type", values[i])
			} else if value.Valid {
				_m.ReferenceType = value.String
			}
		case ledgertransaction.FieldReferenceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field reference_id", values[i])
			} else if value != nil {
				_m.ReferenceID = *value
			}
		case ledgertransaction.FieldTransactionDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_date", values[i])
			} else if value.Valid {
				_m.TransactionDate = value.Time
			}
		case ledgertransaction.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case ledgertransaction.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case ledgertransaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LedgerTransaction.
// This includes values selected through modifiers, order, etc.
func (_m *LedgerTransaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the LedgerTransaction entity.
func (_m *LedgerTransaction) QueryAccount() *ChartOfAccountQuery {
	return NewLedgerTransactionClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this LedgerTransaction.
// Note that you need to call LedgerTransaction.Unwrap() before calling this method if this LedgerTransaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LedgerTransaction) Update() *LedgerTransactionUpdateOne {
	return NewLedgerTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LedgerTransaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LedgerTransaction) Unwrap() *LedgerTransaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LedgerTransaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LedgerTransaction) String() string {
	var builder strings.Builder
	builder.WriteString("LedgerTransaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("journal_entry_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.JournalEntryID))
	builder.WriteString(", ")
	builder.WriteString("debit_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DebitAmount))
	builder.WriteString(", ")
	builder.WriteString("credit_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditAmount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("exchange_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExchangeRate))
	builder.WriteString(", ")
	builder.WriteString("reference_type=")
	builder.WriteString(_m.ReferenceType)
	builder.WriteString(", ")
	builder.WriteString("reference_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferenceID))
	builder.WriteString(", ")
	builder.WriteString("transaction_date=")
	builder.WriteString(_m.TransactionDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LedgerTransactions is a parsable slice of LedgerTransaction.
type LedgerTransactions []*LedgerTransaction
