// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/treasury-api/internal/ent/paymenttransaction"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// PaymentTransaction is the model entity for the PaymentTransaction schema.
type PaymentTransaction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Tenant identifier
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Payment intent identifier
	PaymentIntentID uuid.UUID `json:"payment_intent_id,omitempty"`
	// Transaction type: payment, refund, chargeback, adjustment
	TransactionType string `json:"transaction_type,omitempty"`
	// Transaction amount
	Amount decimal.Decimal `json:"amount,omitempty"`
	// ISO currency code
	Currency string `json:"currency,omitempty"`
	// Payment provider: mpesa, stripe, paypal, blockchain
	Provider string `json:"provider,omitempty"`
	// Provider transaction reference
	ProviderReference string `json:"provider_reference,omitempty"`
	// Status: pending, processing, succeeded, failed, cancelled
	Status string `json:"status,omitempty"`
	// Processing timestamp
	ProcessedAt time.Time `json:"processed_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentTransaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymenttransaction.FieldMetadata:
			values[i] = new([]byte)
		case paymenttransaction.FieldAmount:
			values[i] = new(decimal.Decimal)
		case paymenttransaction.FieldTransactionType, paymenttransaction.FieldCurrency, paymenttransaction.FieldProvider, paymenttransaction.FieldProviderReference, paymenttransaction.FieldStatus:
			values[i] = new(sql.NullString)
		case paymenttransaction.FieldProcessedAt, paymenttransaction.FieldCreatedAt, paymenttransaction.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case paymenttransaction.FieldID, paymenttransaction.FieldTenantID, paymenttransaction.FieldPaymentIntentID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentTransaction fields.
func (_m *PaymentTransaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymenttransaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case paymenttransaction.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case paymenttransaction.FieldPaymentIntentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field payment_intent_id", values[i])
			} else if value != nil {
				_m.PaymentIntentID = *value
			}
		case paymenttransaction.FieldTransactionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_type", values[i])
			} else if value.Valid {
				_m.TransactionType = value.String
			}
		case paymenttransaction.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				_m.Amount = *value
			}
		case paymenttransaction.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymenttransaction.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case paymenttransaction.FieldProviderReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_reference", values[i])
			} else if value.Valid {
				_m.ProviderReference = value.String
			}
		case paymenttransaction.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymenttransaction.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = value.Time
			}
		case paymenttransaction.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case paymenttransaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymenttransaction.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentTransaction.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentTransaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentTransaction.
// Note that you need to call PaymentTransaction.Unwrap() before calling this method if this PaymentTransaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentTransaction) Update() *PaymentTransactionUpdateOne {
	return NewPaymentTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentTransaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentTransaction) Unwrap() *PaymentTransaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentTransaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentTransaction) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentTransaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("payment_intent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentIntentID))
	builder.WriteString(", ")
	builder.WriteString("transaction_type=")
	builder.WriteString(_m.TransactionType)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_reference=")
	builder.WriteString(_m.ProviderReference)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("processed_at=")
	builder.WriteString(_m.ProcessedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentTransactions is a parsable slice of PaymentTransaction.
type PaymentTransactions []*PaymentTransaction
