// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bengobox/treasury-api/internal/ent/chartofaccount"
	"github.com/bengobox/treasury-api/internal/ent/invoice"
	"github.com/bengobox/treasury-api/internal/ent/ledgertransaction"
	"github.com/bengobox/treasury-api/internal/ent/outboxevent"
	"github.com/bengobox/treasury-api/internal/ent/paymentintent"
	"github.com/bengobox/treasury-api/internal/ent/paymenttransaction"
	"github.com/bengobox/treasury-api/internal/ent/schema"
	"github.com/bengobox/treasury-api/internal/ent/treasurypermission"
	"github.com/bengobox/treasury-api/internal/ent/treasuryrole"
	"github.com/bengobox/treasury-api/internal/ent/treasuryuser"
	"github.com/bengobox/treasury-api/internal/ent/userroleassignment"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chartofaccountFields := schema.ChartOfAccount{}.Fields()
	_ = chartofaccountFields
	// chartofaccountDescAccountCode is the schema descriptor for account_code field.
	chartofaccountDescAccountCode := chartofaccountFields[2].Descriptor()
	// chartofaccount.AccountCodeValidator is a validator for the "account_code" field. It is called by the builders before save.
	chartofaccount.AccountCodeValidator = chartofaccountDescAccountCode.Validators[0].(func(string) error)
	// chartofaccountDescAccountName is the schema descriptor for account_name field.
	chartofaccountDescAccountName := chartofaccountFields[3].Descriptor()
	// chartofaccount.AccountNameValidator is a validator for the "account_name" field. It is called by the builders before save.
	chartofaccount.AccountNameValidator = chartofaccountDescAccountName.Validators[0].(func(string) error)
	// chartofaccountDescAccountType is the schema descriptor for account_type field.
	chartofaccountDescAccountType := chartofaccountFields[4].Descriptor()
	// chartofaccount.AccountTypeValidator is a validator for the "account_type" field. It is called by the builders before save.
	chartofaccount.AccountTypeValidator = chartofaccountDescAccountType.Validators[0].(func(string) error)
	// chartofaccountDescIsActive is the schema descriptor for is_active field.
	chartofaccountDescIsActive := chartofaccountFields[6].Descriptor()
	// chartofaccount.DefaultIsActive holds the default value on creation for the is_active field.
	chartofaccount.DefaultIsActive = chartofaccountDescIsActive.Default.(bool)
	// chartofaccountDescMetadata is the schema descriptor for metadata field.
	chartofaccountDescMetadata := chartofaccountFields[8].Descriptor()
	// chartofaccount.DefaultMetadata holds the default value on creation for the metadata field.
	chartofaccount.DefaultMetadata = chartofaccountDescMetadata.Default.(map[string]interface{})
	// chartofaccountDescCreatedAt is the schema descriptor for created_at field.
	chartofaccountDescCreatedAt := chartofaccountFields[9].Descriptor()
	// chartofaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	chartofaccount.DefaultCreatedAt = chartofaccountDescCreatedAt.Default.(func() time.Time)
	// chartofaccountDescUpdatedAt is the schema descriptor for updated_at field.
	chartofaccountDescUpdatedAt := chartofaccountFields[10].Descriptor()
	// chartofaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chartofaccount.DefaultUpdatedAt = chartofaccountDescUpdatedAt.Default.(func() time.Time)
	// chartofaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chartofaccount.UpdateDefaultUpdatedAt = chartofaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// chartofaccountDescID is the schema descriptor for id field.
	chartofaccountDescID := chartofaccountFields[0].Descriptor()
	// chartofaccount.DefaultID holds the default value on creation for the id field.
	chartofaccount.DefaultID = chartofaccountDescID.Default.(func() uuid.UUID)
	invoiceFields := schema.Invoice{}.Fields()
	_ = invoiceFields
	// invoiceDescInvoiceNumber is the schema descriptor for invoice_number field.
	invoiceDescInvoiceNumber := invoiceFields[2].Descriptor()
	// invoice.InvoiceNumberValidator is a validator for the "invoice_number" field. It is called by the builders before save.
	invoice.InvoiceNumberValidator = invoiceDescInvoiceNumber.Validators[0].(func(string) error)
	// invoiceDescInvoiceType is the schema descriptor for invoice_type field.
	invoiceDescInvoiceType := invoiceFields[4].Descriptor()
	// invoice.DefaultInvoiceType holds the default value on creation for the invoice_type field.
	invoice.DefaultInvoiceType = invoiceDescInvoiceType.Default.(string)
	// invoiceDescTaxAmount is the schema descriptor for tax_amount field.
	invoiceDescTaxAmount := invoiceFields[8].Descriptor()
	// invoice.DefaultTaxAmount holds the default value on creation for the tax_amount field.
	invoice.DefaultTaxAmount = decimal.Decimal(invoiceDescTaxAmount.Default.(float64))
	// invoiceDescCurrency is the schema descriptor for currency field.
	invoiceDescCurrency := invoiceFields[10].Descriptor()
	// invoice.DefaultCurrency holds the default value on creation for the currency field.
	invoice.DefaultCurrency = invoiceDescCurrency.Default.(string)
	// invoiceDescStatus is the schema descriptor for status field.
	invoiceDescStatus := invoiceFields[11].Descriptor()
	// invoice.DefaultStatus holds the default value on creation for the status field.
	invoice.DefaultStatus = invoiceDescStatus.Default.(string)
	// invoiceDescPaymentStatus is the schema descriptor for payment_status field.
	invoiceDescPaymentStatus := invoiceFields[12].Descriptor()
	// invoice.DefaultPaymentStatus holds the default value on creation for the payment_status field.
	invoice.DefaultPaymentStatus = invoiceDescPaymentStatus.Default.(string)
	// invoiceDescMetadata is the schema descriptor for metadata field.
	invoiceDescMetadata := invoiceFields[15].Descriptor()
	// invoice.DefaultMetadata holds the default value on creation for the metadata field.
	invoice.DefaultMetadata = invoiceDescMetadata.Default.(map[string]interface{})
	// invoiceDescCreatedAt is the schema descriptor for created_at field.
	invoiceDescCreatedAt := invoiceFields[16].Descriptor()
	// invoice.DefaultCreatedAt holds the default value on creation for the created_at field.
	invoice.DefaultCreatedAt = invoiceDescCreatedAt.Default.(func() time.Time)
	// invoiceDescUpdatedAt is the schema descriptor for updated_at field.
	invoiceDescUpdatedAt := invoiceFields[17].Descriptor()
	// invoice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invoice.DefaultUpdatedAt = invoiceDescUpdatedAt.Default.(func() time.Time)
	// invoice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invoice.UpdateDefaultUpdatedAt = invoiceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// invoiceDescID is the schema descriptor for id field.
	invoiceDescID := invoiceFields[0].Descriptor()
	// invoice.DefaultID holds the default value on creation for the id field.
	invoice.DefaultID = invoiceDescID.Default.(func() uuid.UUID)
	ledgertransactionFields := schema.LedgerTransaction{}.Fields()
	_ = ledgertransactionFields
	// ledgertransactionDescDebitAmount is the schema descriptor for debit_amount field.
	ledgertransactionDescDebitAmount := ledgertransactionFields[4].Descriptor()
	// ledgertransaction.DefaultDebitAmount holds the default value on creation for the debit_amount field.
	ledgertransaction.DefaultDebitAmount = decimal.Decimal(ledgertransactionDescDebitAmount.Default.(float64))
	// ledgertransactionDescCreditAmount is the schema descriptor for credit_amount field.
	ledgertransactionDescCreditAmount := ledgertransactionFields[5].Descriptor()
	// ledgertransaction.DefaultCreditAmount holds the default value on creation for the credit_amount field.
	ledgertransaction.DefaultCreditAmount = decimal.Decimal(ledgertransactionDescCreditAmount.Default.(float64))
	// ledgertransactionDescCurrency is the schema descriptor for currency field.
	ledgertransactionDescCurrency := ledgertransactionFields[6].Descriptor()
	// ledgertransaction.DefaultCurrency holds the default value on creation for the currency field.
	ledgertransaction.DefaultCurrency = ledgertransactionDescCurrency.Default.(string)
	// ledgertransactionDescExchangeRate is the schema descriptor for exchange_rate field.
	ledgertransactionDescExchangeRate := ledgertransactionFields[7].Descriptor()
	// ledgertransaction.DefaultExchangeRate holds the default value on creation for the exchange_rate field.
	ledgertransaction.DefaultExchangeRate = decimal.Decimal(ledgertransactionDescExchangeRate.Default.(float64))
	// ledgertransactionDescMetadata is the schema descriptor for metadata field.
	ledgertransactionDescMetadata := ledgertransactionFields[12].Descriptor()
	// ledgertransaction.DefaultMetadata holds the default value on creation for the metadata field.
	ledgertransaction.DefaultMetadata = ledgertransactionDescMetadata.Default.(map[string]interface{})
	// ledgertransactionDescCreatedAt is the schema descriptor for created_at field.
	ledgertransactionDescCreatedAt := ledgertransactionFields[13].Descriptor()
	// ledgertransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	ledgertransaction.DefaultCreatedAt = ledgertransactionDescCreatedAt.Default.(func() time.Time)
	// ledgertransactionDescID is the schema descriptor for id field.
	ledgertransactionDescID := ledgertransactionFields[0].Descriptor()
	// ledgertransaction.DefaultID holds the default value on creation for the id field.
	ledgertransaction.DefaultID = ledgertransactionDescID.Default.(func() uuid.UUID)
	outboxeventFields := schema.OutboxEvent{}.Fields()
	_ = outboxeventFields
	// outboxeventDescAggregateType is the schema descriptor for aggregate_type field.
	outboxeventDescAggregateType := outboxeventFields[2].Descriptor()
	// outboxevent.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	outboxevent.AggregateTypeValidator = outboxeventDescAggregateType.Validators[0].(func(string) error)
	// outboxeventDescEventType is the schema descriptor for event_type field.
	outboxeventDescEventType := outboxeventFields[4].Descriptor()
	// outboxevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	outboxevent.EventTypeValidator = outboxeventDescEventType.Validators[0].(func(string) error)
	// outboxeventDescStatus is the schema descriptor for status field.
	outboxeventDescStatus := outboxeventFields[6].Descriptor()
	// outboxevent.DefaultStatus holds the default value on creation for the status field.
	outboxevent.DefaultStatus = outboxeventDescStatus.Default.(string)
	// outboxeventDescAttempts is the schema descriptor for attempts field.
	outboxeventDescAttempts := outboxeventFields[7].Descriptor()
	// outboxevent.DefaultAttempts holds the default value on creation for the attempts field.
	outboxevent.DefaultAttempts = outboxeventDescAttempts.Default.(int)
	// outboxeventDescCreatedAt is the schema descriptor for created_at field.
	outboxeventDescCreatedAt := outboxeventFields[11].Descriptor()
	// outboxevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxevent.DefaultCreatedAt = outboxeventDescCreatedAt.Default.(func() time.Time)
	// outboxeventDescID is the schema descriptor for id field.
	outboxeventDescID := outboxeventFields[0].Descriptor()
	// outboxevent.DefaultID holds the default value on creation for the id field.
	outboxevent.DefaultID = outboxeventDescID.Default.(func() uuid.UUID)
	paymentintentFields := schema.PaymentIntent{}.Fields()
	_ = paymentintentFields
	// paymentintentDescReferenceID is the schema descriptor for reference_id field.
	paymentintentDescReferenceID := paymentintentFields[2].Descriptor()
	// paymentintent.ReferenceIDValidator is a validator for the "reference_id" field. It is called by the builders before save.
	paymentintent.ReferenceIDValidator = paymentintentDescReferenceID.Validators[0].(func(string) error)
	// paymentintentDescReferenceType is the schema descriptor for reference_type field.
	paymentintentDescReferenceType := paymentintentFields[3].Descriptor()
	// paymentintent.ReferenceTypeValidator is a validator for the "reference_type" field. It is called by the builders before save.
	paymentintent.ReferenceTypeValidator = paymentintentDescReferenceType.Validators[0].(func(string) error)
	// paymentintentDescPaymentMethod is the schema descriptor for payment_method field.
	paymentintentDescPaymentMethod := paymentintentFields[4].Descriptor()
	// paymentintent.PaymentMethodValidator is a validator for the "payment_method" field. It is called by the builders before save.
	paymentintent.PaymentMethodValidator = paymentintentDescPaymentMethod.Validators[0].(func(string) error)
	// paymentintentDescCurrency is the schema descriptor for currency field.
	paymentintentDescCurrency := paymentintentFields[5].Descriptor()
	// paymentintent.DefaultCurrency holds the default value on creation for the currency field.
	paymentintent.DefaultCurrency = paymentintentDescCurrency.Default.(string)
	// paymentintentDescStatus is the schema descriptor for status field.
	paymentintentDescStatus := paymentintentFields[7].Descriptor()
	// paymentintent.DefaultStatus holds the default value on creation for the status field.
	paymentintent.DefaultStatus = paymentintentDescStatus.Default.(string)
	// paymentintentDescMetadata is the schema descriptor for metadata field.
	paymentintentDescMetadata := paymentintentFields[8].Descriptor()
	// paymentintent.DefaultMetadata holds the default value on creation for the metadata field.
	paymentintent.DefaultMetadata = paymentintentDescMetadata.Default.(map[string]interface{})
	// paymentintentDescCreatedAt is the schema descriptor for created_at field.
	paymentintentDescCreatedAt := paymentintentFields[12].Descriptor()
	// paymentintent.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentintent.DefaultCreatedAt = paymentintentDescCreatedAt.Default.(func() time.Time)
	// paymentintentDescUpdatedAt is the schema descriptor for updated_at field.
	paymentintentDescUpdatedAt := paymentintentFields[13].Descriptor()
	// paymentintent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymentintent.DefaultUpdatedAt = paymentintentDescUpdatedAt.Default.(func() time.Time)
	// paymentintent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymentintent.UpdateDefaultUpdatedAt = paymentintentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymentintentDescID is the schema descriptor for id field.
	paymentintentDescID := paymentintentFields[0].Descriptor()
	// paymentintent.DefaultID holds the default value on creation for the id field.
	paymentintent.DefaultID = paymentintentDescID.Default.(func() uuid.UUID)
	paymenttransactionFields := schema.PaymentTransaction{}.Fields()
	_ = paymenttransactionFields
	// paymenttransactionDescTransactionType is the schema descriptor for transaction_type field.
	paymenttransactionDescTransactionType := paymenttransactionFields[3].Descriptor()
	// paymenttransaction.TransactionTypeValidator is a validator for the "transaction_type" field. It is called by the builders before save.
	paymenttransaction.TransactionTypeValidator = paymenttransactionDescTransactionType.Validators[0].(func(string) error)
	// paymenttransactionDescCurrency is the schema descriptor for currency field.
	paymenttransactionDescCurrency := paymenttransactionFields[5].Descriptor()
	// paymenttransaction.DefaultCurrency holds the default value on creation for the currency field.
	paymenttransaction.DefaultCurrency = paymenttransactionDescCurrency.Default.(string)
	// paymenttransactionDescProvider is the schema descriptor for provider field.
	paymenttransactionDescProvider := paymenttransactionFields[6].Descriptor()
	// paymenttransaction.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	paymenttransaction.ProviderValidator = paymenttransactionDescProvider.Validators[0].(func(string) error)
	// paymenttransactionDescProviderReference is the schema descriptor for provider_reference field.
	paymenttransactionDescProviderReference := paymenttransactionFields[7].Descriptor()
	// paymenttransaction.ProviderReferenceValidator is a validator for the "provider_reference" field. It is called by the builders before save.
	paymenttransaction.ProviderReferenceValidator = paymenttransactionDescProviderReference.Validators[0].(func(string) error)
	// paymenttransactionDescStatus is the schema descriptor for status field.
	paymenttransactionDescStatus := paymenttransactionFields[8].Descriptor()
	// paymenttransaction.DefaultStatus holds the default value on creation for the status field.
	paymenttransaction.DefaultStatus = paymenttransactionDescStatus.Default.(string)
	// paymenttransactionDescMetadata is the schema descriptor for metadata field.
	paymenttransactionDescMetadata := paymenttransactionFields[10].Descriptor()
	// paymenttransaction.DefaultMetadata holds the default value on creation for the metadata field.
	paymenttransaction.DefaultMetadata = paymenttransactionDescMetadata.Default.(map[string]interface{})
	// paymenttransactionDescCreatedAt is the schema descriptor for created_at field.
	paymenttransactionDescCreatedAt := paymenttransactionFields[11].Descriptor()
	// paymenttransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymenttransaction.DefaultCreatedAt = paymenttransactionDescCreatedAt.Default.(func() time.Time)
	// paymenttransactionDescUpdatedAt is the schema descriptor for updated_at field.
	paymenttransactionDescUpdatedAt := paymenttransactionFields[12].Descriptor()
	// paymenttransaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymenttransaction.DefaultUpdatedAt = paymenttransactionDescUpdatedAt.Default.(func() time.Time)
	// paymenttransaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymenttransaction.UpdateDefaultUpdatedAt = paymenttransactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymenttransactionDescID is the schema descriptor for id field.
	paymenttransactionDescID := paymenttransactionFields[0].Descriptor()
	// paymenttransaction.DefaultID holds the default value on creation for the id field.
	paymenttransaction.DefaultID = paymenttransactionDescID.Default.(func() uuid.UUID)
	treasurypermissionFields := schema.TreasuryPermission{}.Fields()
	_ = treasurypermissionFields
	// treasurypermissionDescPermissionCode is the schema descriptor for permission_code field.
	treasurypermissionDescPermissionCode := treasurypermissionFields[1].Descriptor()
	// treasurypermission.PermissionCodeValidator is a validator for the "permission_code" field. It is called by the builders before save.
	treasurypermission.PermissionCodeValidator = treasurypermissionDescPermissionCode.Validators[0].(func(string) error)
	// treasurypermissionDescName is the schema descriptor for name field.
	treasurypermissionDescName := treasurypermissionFields[2].Descriptor()
	// treasurypermission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	treasurypermission.NameValidator = treasurypermissionDescName.Validators[0].(func(string) error)
	// treasurypermissionDescModule is the schema descriptor for module field.
	treasurypermissionDescModule := treasurypermissionFields[3].Descriptor()
	// treasurypermission.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	treasurypermission.ModuleValidator = treasurypermissionDescModule.Validators[0].(func(string) error)
	// treasurypermissionDescAction is the schema descriptor for action field.
	treasurypermissionDescAction := treasurypermissionFields[4].Descriptor()
	// treasurypermission.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	treasurypermission.ActionValidator = treasurypermissionDescAction.Validators[0].(func(string) error)
	// treasurypermissionDescCreatedAt is the schema descriptor for created_at field.
	treasurypermissionDescCreatedAt := treasurypermissionFields[7].Descriptor()
	// treasurypermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	treasurypermission.DefaultCreatedAt = treasurypermissionDescCreatedAt.Default.(func() time.Time)
	// treasurypermissionDescID is the schema descriptor for id field.
	treasurypermissionDescID := treasurypermissionFields[0].Descriptor()
	// treasurypermission.DefaultID holds the default value on creation for the id field.
	treasurypermission.DefaultID = treasurypermissionDescID.Default.(func() uuid.UUID)
	treasuryroleFields := schema.TreasuryRole{}.Fields()
	_ = treasuryroleFields
	// treasuryroleDescRoleCode is the schema descriptor for role_code field.
	treasuryroleDescRoleCode := treasuryroleFields[2].Descriptor()
	// treasuryrole.RoleCodeValidator is a validator for the "role_code" field. It is called by the builders before save.
	treasuryrole.RoleCodeValidator = treasuryroleDescRoleCode.Validators[0].(func(string) error)
	// treasuryroleDescName is the schema descriptor for name field.
	treasuryroleDescName := treasuryroleFields[3].Descriptor()
	// treasuryrole.NameValidator is a validator for the "name" field. It is called by the builders before save.
	treasuryrole.NameValidator = treasuryroleDescName.Validators[0].(func(string) error)
	// treasuryroleDescIsSystemRole is the schema descriptor for is_system_role field.
	treasuryroleDescIsSystemRole := treasuryroleFields[5].Descriptor()
	// treasuryrole.DefaultIsSystemRole holds the default value on creation for the is_system_role field.
	treasuryrole.DefaultIsSystemRole = treasuryroleDescIsSystemRole.Default.(bool)
	// treasuryroleDescCreatedAt is the schema descriptor for created_at field.
	treasuryroleDescCreatedAt := treasuryroleFields[6].Descriptor()
	// treasuryrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	treasuryrole.DefaultCreatedAt = treasuryroleDescCreatedAt.Default.(func() time.Time)
	// treasuryroleDescUpdatedAt is the schema descriptor for updated_at field.
	treasuryroleDescUpdatedAt := treasuryroleFields[7].Descriptor()
	// treasuryrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	treasuryrole.DefaultUpdatedAt = treasuryroleDescUpdatedAt.Default.(func() time.Time)
	// treasuryrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	treasuryrole.UpdateDefaultUpdatedAt = treasuryroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// treasuryroleDescID is the schema descriptor for id field.
	treasuryroleDescID := treasuryroleFields[0].Descriptor()
	// treasuryrole.DefaultID holds the default value on creation for the id field.
	treasuryrole.DefaultID = treasuryroleDescID.Default.(func() uuid.UUID)
	treasuryuserFields := schema.TreasuryUser{}.Fields()
	_ = treasuryuserFields
	// treasuryuserDescEmail is the schema descriptor for email field.
	treasuryuserDescEmail := treasuryuserFields[3].Descriptor()
	// treasuryuser.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	treasuryuser.EmailValidator = treasuryuserDescEmail.Validators[0].(func(string) error)
	// treasuryuserDescStatus is the schema descriptor for status field.
	treasuryuserDescStatus := treasuryuserFields[4].Descriptor()
	// treasuryuser.DefaultStatus holds the default value on creation for the status field.
	treasuryuser.DefaultStatus = treasuryuserDescStatus.Default.(string)
	// treasuryuserDescSyncStatus is the schema descriptor for sync_status field.
	treasuryuserDescSyncStatus := treasuryuserFields[5].Descriptor()
	// treasuryuser.DefaultSyncStatus holds the default value on creation for the sync_status field.
	treasuryuser.DefaultSyncStatus = treasuryuserDescSyncStatus.Default.(string)
	// treasuryuserDescCreatedAt is the schema descriptor for created_at field.
	treasuryuserDescCreatedAt := treasuryuserFields[7].Descriptor()
	// treasuryuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	treasuryuser.DefaultCreatedAt = treasuryuserDescCreatedAt.Default.(func() time.Time)
	// treasuryuserDescUpdatedAt is the schema descriptor for updated_at field.
	treasuryuserDescUpdatedAt := treasuryuserFields[8].Descriptor()
	// treasuryuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	treasuryuser.DefaultUpdatedAt = treasuryuserDescUpdatedAt.Default.(func() time.Time)
	// treasuryuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	treasuryuser.UpdateDefaultUpdatedAt = treasuryuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// treasuryuserDescID is the schema descriptor for id field.
	treasuryuserDescID := treasuryuserFields[0].Descriptor()
	// treasuryuser.DefaultID holds the default value on creation for the id field.
	treasuryuser.DefaultID = treasuryuserDescID.Default.(func() uuid.UUID)
	userroleassignmentFields := schema.UserRoleAssignment{}.Fields()
	_ = userroleassignmentFields
	// userroleassignmentDescAssignedAt is the schema descriptor for assigned_at field.
	userroleassignmentDescAssignedAt := userroleassignmentFields[5].Descriptor()
	// userroleassignment.DefaultAssignedAt holds the default value on creation for the assigned_at field.
	userroleassignment.DefaultAssignedAt = userroleassignmentDescAssignedAt.Default.(func() time.Time)
	// userroleassignmentDescID is the schema descriptor for id field.
	userroleassignmentDescID := userroleassignmentFields[0].Descriptor()
	// userroleassignment.DefaultID holds the default value on creation for the id field.
	userroleassignment.DefaultID = userroleassignmentDescID.Default.(func() uuid.UUID)
}
