// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/treasury-api/internal/ent/predicate"
	"github.com/bengobox/treasury-api/internal/ent/rolepermission"
	"github.com/bengobox/treasury-api/internal/ent/treasurypermission"
	"github.com/bengobox/treasury-api/internal/ent/treasuryrole"
	"github.com/bengobox/treasury-api/internal/ent/userroleassignment"
	"github.com/google/uuid"
)

// TreasuryRoleUpdate is the builder for updating TreasuryRole entities.
type TreasuryRoleUpdate struct {
	config
	hooks    []Hook
	mutation *TreasuryRoleMutation
}

// Where appends a list predicates to the TreasuryRoleUpdate builder.
func (_u *TreasuryRoleUpdate) Where(ps ...predicate.TreasuryRole) *TreasuryRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TreasuryRoleUpdate) SetTenantID(v uuid.UUID) *TreasuryRoleUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TreasuryRoleUpdate) SetNillableTenantID(v *uuid.UUID) *TreasuryRoleUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *TreasuryRoleUpdate) SetRoleCode(v string) *TreasuryRoleUpdate {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *TreasuryRoleUpdate) SetNillableRoleCode(v *string) *TreasuryRoleUpdate {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TreasuryRoleUpdate) SetName(v string) *TreasuryRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TreasuryRoleUpdate) SetNillableName(v *string) *TreasuryRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TreasuryRoleUpdate) SetDescription(v string) *TreasuryRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TreasuryRoleUpdate) SetNillableDescription(v *string) *TreasuryRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TreasuryRoleUpdate) ClearDescription() *TreasuryRoleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsSystemRole sets the "is_system_role" field.
func (_u *TreasuryRoleUpdate) SetIsSystemRole(v bool) *TreasuryRoleUpdate {
	_u.mutation.SetIsSystemRole(v)
	return _u
}

// SetNillableIsSystemRole sets the "is_system_role" field if the given value is not nil.
func (_u *TreasuryRoleUpdate) SetNillableIsSystemRole(v *bool) *TreasuryRoleUpdate {
	if v != nil {
		_u.SetIsSystemRole(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TreasuryRoleUpdate) SetUpdatedAt(v time.Time) *TreasuryRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the TreasuryPermission entity by IDs.
func (_u *TreasuryRoleUpdate) AddPermissionIDs(ids ...uuid.UUID) *TreasuryRoleUpdate {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the TreasuryPermission entity.
func (_u *TreasuryRoleUpdate) AddPermissions(v ...*TreasuryPermission) *TreasuryRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignments" edge to the UserRoleAssignment entity by IDs.
func (_u *TreasuryRoleUpdate) AddUserAssignmentIDs(ids ...uuid.UUID) *TreasuryRoleUpdate {
	_u.mutation.AddUserAssignmentIDs(ids...)
	return _u
}

// AddUserAssignments adds the "user_assignments" edges to the UserRoleAssignment entity.
func (_u *TreasuryRoleUpdate) AddUserAssignments(v ...*UserRoleAssignment) *TreasuryRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserAssignmentIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermission entity by IDs.
func (_u *TreasuryRoleUpdate) AddRolePermissionIDs(ids ...int) *TreasuryRoleUpdate {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermission entity.
func (_u *TreasuryRoleUpdate) AddRolePermissions(v ...*RolePermission) *TreasuryRoleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// Mutation returns the TreasuryRoleMutation object of the builder.
func (_u *TreasuryRoleUpdate) Mutation() *TreasuryRoleMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the TreasuryPermission entity.
func (_u *TreasuryRoleUpdate) ClearPermissions() *TreasuryRoleUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to TreasuryPermission entities by IDs.
func (_u *TreasuryRoleUpdate) RemovePermissionIDs(ids ...uuid.UUID) *TreasuryRoleUpdate {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to TreasuryPermission entities.
func (_u *TreasuryRoleUpdate) RemovePermissions(v ...*TreasuryPermission) *TreasuryRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearUserAssignments clears all "user_assignments" edges to the UserRoleAssignment entity.
func (_u *TreasuryRoleUpdate) ClearUserAssignments() *TreasuryRoleUpdate {
	_u.mutation.ClearUserAssignments()
	return _u
}

// RemoveUserAssignmentIDs removes the "user_assignments" edge to UserRoleAssignment entities by IDs.
func (_u *TreasuryRoleUpdate) RemoveUserAssignmentIDs(ids ...uuid.UUID) *TreasuryRoleUpdate {
	_u.mutation.RemoveUserAssignmentIDs(ids...)
	return _u
}

// RemoveUserAssignments removes "user_assignments" edges to UserRoleAssignment entities.
func (_u *TreasuryRoleUpdate) RemoveUserAssignments(v ...*UserRoleAssignment) *TreasuryRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserAssignmentIDs(ids...)
}

// ClearRolePermissions clears all "role_permissions" edges to the RolePermission entity.
func (_u *TreasuryRoleUpdate) ClearRolePermissions() *TreasuryRoleUpdate {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RolePermission entities by IDs.
func (_u *TreasuryRoleUpdate) RemoveRolePermissionIDs(ids ...int) *TreasuryRoleUpdate {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RolePermission entities.
func (_u *TreasuryRoleUpdate) RemoveRolePermissions(v ...*RolePermission) *TreasuryRoleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TreasuryRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TreasuryRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TreasuryRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TreasuryRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TreasuryRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := treasuryrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TreasuryRoleUpdate) check() error {
	if v, ok := _u.mutation.RoleCode(); ok {
		if err := treasuryrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "TreasuryRole.role_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := treasuryrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TreasuryRole.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TreasuryRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(treasuryrole.Table, treasuryrole.Columns, sqlgraph.NewFieldSpec(treasuryrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(treasuryrole.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(treasuryrole.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(treasuryrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(treasuryrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(treasuryrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsSystemRole(); ok {
		_spec.SetField(treasuryrole.FieldIsSystemRole, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(treasuryrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   treasuryrole.PermissionsTable,
			Columns: treasuryrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasurypermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   treasuryrole.PermissionsTable,
			Columns: treasuryrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasurypermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   treasuryrole.PermissionsTable,
			Columns: treasuryrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasurypermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treasuryrole.UserAssignmentsTable,
			Columns: []string{treasuryrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treasuryrole.UserAssignmentsTable,
			Columns: []string{treasuryrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treasuryrole.UserAssignmentsTable,
			Columns: []string{treasuryrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   treasuryrole.RolePermissionsTable,
			Columns: []string{treasuryrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   treasuryrole.RolePermissionsTable,
			Columns: []string{treasuryrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   treasuryrole.RolePermissionsTable,
			Columns: []string{treasuryrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{treasuryrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TreasuryRoleUpdateOne is the builder for updating a single TreasuryRole entity.
type TreasuryRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TreasuryRoleMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TreasuryRoleUpdateOne) SetTenantID(v uuid.UUID) *TreasuryRoleUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TreasuryRoleUpdateOne) SetNillableTenantID(v *uuid.UUID) *TreasuryRoleUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *TreasuryRoleUpdateOne) SetRoleCode(v string) *TreasuryRoleUpdateOne {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *TreasuryRoleUpdateOne) SetNillableRoleCode(v *string) *TreasuryRoleUpdateOne {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TreasuryRoleUpdateOne) SetName(v string) *TreasuryRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TreasuryRoleUpdateOne) SetNillableName(v *string) *TreasuryRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TreasuryRoleUpdateOne) SetDescription(v string) *TreasuryRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TreasuryRoleUpdateOne) SetNillableDescription(v *string) *TreasuryRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TreasuryRoleUpdateOne) ClearDescription() *TreasuryRoleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsSystemRole sets the "is_system_role" field.
func (_u *TreasuryRoleUpdateOne) SetIsSystemRole(v bool) *TreasuryRoleUpdateOne {
	_u.mutation.SetIsSystemRole(v)
	return _u
}

// SetNillableIsSystemRole sets the "is_system_role" field if the given value is not nil.
func (_u *TreasuryRoleUpdateOne) SetNillableIsSystemRole(v *bool) *TreasuryRoleUpdateOne {
	if v != nil {
		_u.SetIsSystemRole(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TreasuryRoleUpdateOne) SetUpdatedAt(v time.Time) *TreasuryRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPermissionIDs adds the "permissions" edge to the TreasuryPermission entity by IDs.
func (_u *TreasuryRoleUpdateOne) AddPermissionIDs(ids ...uuid.UUID) *TreasuryRoleUpdateOne {
	_u.mutation.AddPermissionIDs(ids...)
	return _u
}

// AddPermissions adds the "permissions" edges to the TreasuryPermission entity.
func (_u *TreasuryRoleUpdateOne) AddPermissions(v ...*TreasuryPermission) *TreasuryRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPermissionIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignments" edge to the UserRoleAssignment entity by IDs.
func (_u *TreasuryRoleUpdateOne) AddUserAssignmentIDs(ids ...uuid.UUID) *TreasuryRoleUpdateOne {
	_u.mutation.AddUserAssignmentIDs(ids...)
	return _u
}

// AddUserAssignments adds the "user_assignments" edges to the UserRoleAssignment entity.
func (_u *TreasuryRoleUpdateOne) AddUserAssignments(v ...*UserRoleAssignment) *TreasuryRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserAssignmentIDs(ids...)
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermission entity by IDs.
func (_u *TreasuryRoleUpdateOne) AddRolePermissionIDs(ids ...int) *TreasuryRoleUpdateOne {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermission entity.
func (_u *TreasuryRoleUpdateOne) AddRolePermissions(v ...*RolePermission) *TreasuryRoleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// Mutation returns the TreasuryRoleMutation object of the builder.
func (_u *TreasuryRoleUpdateOne) Mutation() *TreasuryRoleMutation {
	return _u.mutation
}

// ClearPermissions clears all "permissions" edges to the TreasuryPermission entity.
func (_u *TreasuryRoleUpdateOne) ClearPermissions() *TreasuryRoleUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// RemovePermissionIDs removes the "permissions" edge to TreasuryPermission entities by IDs.
func (_u *TreasuryRoleUpdateOne) RemovePermissionIDs(ids ...uuid.UUID) *TreasuryRoleUpdateOne {
	_u.mutation.RemovePermissionIDs(ids...)
	return _u
}

// RemovePermissions removes "permissions" edges to TreasuryPermission entities.
func (_u *TreasuryRoleUpdateOne) RemovePermissions(v ...*TreasuryPermission) *TreasuryRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePermissionIDs(ids...)
}

// ClearUserAssignments clears all "user_assignments" edges to the UserRoleAssignment entity.
func (_u *TreasuryRoleUpdateOne) ClearUserAssignments() *TreasuryRoleUpdateOne {
	_u.mutation.ClearUserAssignments()
	return _u
}

// RemoveUserAssignmentIDs removes the "user_assignments" edge to UserRoleAssignment entities by IDs.
func (_u *TreasuryRoleUpdateOne) RemoveUserAssignmentIDs(ids ...uuid.UUID) *TreasuryRoleUpdateOne {
	_u.mutation.RemoveUserAssignmentIDs(ids...)
	return _u
}

// RemoveUserAssignments removes "user_assignments" edges to UserRoleAssignment entities.
func (_u *TreasuryRoleUpdateOne) RemoveUserAssignments(v ...*UserRoleAssignment) *TreasuryRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserAssignmentIDs(ids...)
}

// ClearRolePermissions clears all "role_permissions" edges to the RolePermission entity.
func (_u *TreasuryRoleUpdateOne) ClearRolePermissions() *TreasuryRoleUpdateOne {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to RolePermission entities by IDs.
func (_u *TreasuryRoleUpdateOne) RemoveRolePermissionIDs(ids ...int) *TreasuryRoleUpdateOne {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to RolePermission entities.
func (_u *TreasuryRoleUpdateOne) RemoveRolePermissions(v ...*RolePermission) *TreasuryRoleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// Where appends a list predicates to the TreasuryRoleUpdate builder.
func (_u *TreasuryRoleUpdateOne) Where(ps ...predicate.TreasuryRole) *TreasuryRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TreasuryRoleUpdateOne) Select(field string, fields ...string) *TreasuryRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TreasuryRole entity.
func (_u *TreasuryRoleUpdateOne) Save(ctx context.Context) (*TreasuryRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TreasuryRoleUpdateOne) SaveX(ctx context.Context) *TreasuryRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TreasuryRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TreasuryRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TreasuryRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := treasuryrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TreasuryRoleUpdateOne) check() error {
	if v, ok := _u.mutation.RoleCode(); ok {
		if err := treasuryrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "TreasuryRole.role_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := treasuryrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TreasuryRole.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TreasuryRoleUpdateOne) sqlSave(ctx context.Context) (_node *TreasuryRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(treasuryrole.Table, treasuryrole.Columns, sqlgraph.NewFieldSpec(treasuryrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TreasuryRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, treasuryrole.FieldID)
		for _, f := range fields {
			if !treasuryrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != treasuryrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(treasuryrole.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(treasuryrole.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(treasuryrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(treasuryrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(treasuryrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsSystemRole(); ok {
		_spec.SetField(treasuryrole.FieldIsSystemRole, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(treasuryrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   treasuryrole.PermissionsTable,
			Columns: treasuryrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasurypermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !_u.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   treasuryrole.PermissionsTable,
			Columns: treasuryrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasurypermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   treasuryrole.PermissionsTable,
			Columns: treasuryrole.PermissionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasurypermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treasuryrole.UserAssignmentsTable,
			Columns: []string{treasuryrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.UserAssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treasuryrole.UserAssignmentsTable,
			Columns: []string{treasuryrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   treasuryrole.UserAssignmentsTable,
			Columns: []string{treasuryrole.UserAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   treasuryrole.RolePermissionsTable,
			Columns: []string{treasuryrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   treasuryrole.RolePermissionsTable,
			Columns: []string{treasuryrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   treasuryrole.RolePermissionsTable,
			Columns: []string{treasuryrole.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TreasuryRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{treasuryrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
