// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/treasury-api/internal/ent/treasuryrole"
	"github.com/google/uuid"
)

// TreasuryRole is the model entity for the TreasuryRole schema.
type TreasuryRole struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Tenant identifier
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Role code: finance_admin, accountant, cashier, approver, viewer
	RoleCode string `json:"role_code,omitempty"`
	// Display name
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// System roles cannot be deleted
	IsSystemRole bool `json:"is_system_role,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TreasuryRoleQuery when eager-loading is set.
	Edges        TreasuryRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TreasuryRoleEdges holds the relations/edges for other nodes in the graph.
type TreasuryRoleEdges struct {
	// Permissions holds the value of the permissions edge.
	Permissions []*TreasuryPermission `json:"permissions,omitempty"`
	// UserAssignments holds the value of the user_assignments edge.
	UserAssignments []*UserRoleAssignment `json:"user_assignments,omitempty"`
	// RolePermissions holds the value of the role_permissions edge.
	RolePermissions []*RolePermission `json:"role_permissions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e TreasuryRoleEdges) PermissionsOrErr() ([]*TreasuryPermission, error) {
	if e.loadedTypes[0] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// UserAssignmentsOrErr returns the UserAssignments value or an error if the edge
// was not loaded in eager-loading.
func (e TreasuryRoleEdges) UserAssignmentsOrErr() ([]*UserRoleAssignment, error) {
	if e.loadedTypes[1] {
		return e.UserAssignments, nil
	}
	return nil, &NotLoadedError{edge: "user_assignments"}
}

// RolePermissionsOrErr returns the RolePermissions value or an error if the edge
// was not loaded in eager-loading.
func (e TreasuryRoleEdges) RolePermissionsOrErr() ([]*RolePermission, error) {
	if e.loadedTypes[2] {
		return e.RolePermissions, nil
	}
	return nil, &NotLoadedError{edge: "role_permissions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TreasuryRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case treasuryrole.FieldIsSystemRole:
			values[i] = new(sql.NullBool)
		case treasuryrole.FieldRoleCode, treasuryrole.FieldName, treasuryrole.FieldDescription:
			values[i] = new(sql.NullString)
		case treasuryrole.FieldCreatedAt, treasuryrole.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case treasuryrole.FieldID, treasuryrole.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TreasuryRole fields.
func (_m *TreasuryRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case treasuryrole.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case treasuryrole.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case treasuryrole.FieldRoleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_code", values[i])
			} else if value.Valid {
				_m.RoleCode = value.String
			}
		case treasuryrole.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case treasuryrole.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case treasuryrole.FieldIsSystemRole:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_system_role", values[i])
			} else if value.Valid {
				_m.IsSystemRole = value.Bool
			}
		case treasuryrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case treasuryrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TreasuryRole.
// This includes values selected through modifiers, order, etc.
func (_m *TreasuryRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPermissions queries the "permissions" edge of the TreasuryRole entity.
func (_m *TreasuryRole) QueryPermissions() *TreasuryPermissionQuery {
	return NewTreasuryRoleClient(_m.config).QueryPermissions(_m)
}

// QueryUserAssignments queries the "user_assignments" edge of the TreasuryRole entity.
func (_m *TreasuryRole) QueryUserAssignments() *UserRoleAssignmentQuery {
	return NewTreasuryRoleClient(_m.config).QueryUserAssignments(_m)
}

// QueryRolePermissions queries the "role_permissions" edge of the TreasuryRole entity.
func (_m *TreasuryRole) QueryRolePermissions() *RolePermissionQuery {
	return NewTreasuryRoleClient(_m.config).QueryRolePermissions(_m)
}

// Update returns a builder for updating this TreasuryRole.
// Note that you need to call TreasuryRole.Unwrap() before calling this method if this TreasuryRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TreasuryRole) Update() *TreasuryRoleUpdateOne {
	return NewTreasuryRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TreasuryRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TreasuryRole) Unwrap() *TreasuryRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TreasuryRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TreasuryRole) String() string {
	var builder strings.Builder
	builder.WriteString("TreasuryRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("role_code=")
	builder.WriteString(_m.RoleCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("is_system_role=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSystemRole))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TreasuryRoles is a parsable slice of TreasuryRole.
type TreasuryRoles []*TreasuryRole
