// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/treasury-api/internal/ent/treasuryuser"
	"github.com/google/uuid"
)

// TreasuryUser is the model entity for the TreasuryUser schema.
type TreasuryUser struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Tenant identifier
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Reference to auth-service user (no duplication)
	AuthServiceUserID uuid.UUID `json:"auth_service_user_id,omitempty"`
	// Denormalized email for convenience
	Email string `json:"email,omitempty"`
	// Status: active, inactive, suspended
	Status string `json:"status,omitempty"`
	// Sync status: synced, pending, failed
	SyncStatus string `json:"sync_status,omitempty"`
	// LastSyncAt holds the value of the "last_sync_at" field.
	LastSyncAt time.Time `json:"last_sync_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TreasuryUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case treasuryuser.FieldEmail, treasuryuser.FieldStatus, treasuryuser.FieldSyncStatus:
			values[i] = new(sql.NullString)
		case treasuryuser.FieldLastSyncAt, treasuryuser.FieldCreatedAt, treasuryuser.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case treasuryuser.FieldID, treasuryuser.FieldTenantID, treasuryuser.FieldAuthServiceUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TreasuryUser fields.
func (_m *TreasuryUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case treasuryuser.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case treasuryuser.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case treasuryuser.FieldAuthServiceUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field auth_service_user_id", values[i])
			} else if value != nil {
				_m.AuthServiceUserID = *value
			}
		case treasuryuser.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case treasuryuser.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case treasuryuser.FieldSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_status", values[i])
			} else if value.Valid {
				_m.SyncStatus = value.String
			}
		case treasuryuser.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				_m.LastSyncAt = value.Time
			}
		case treasuryuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case treasuryuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TreasuryUser.
// This includes values selected through modifiers, order, etc.
func (_m *TreasuryUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TreasuryUser.
// Note that you need to call TreasuryUser.Unwrap() before calling this method if this TreasuryUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TreasuryUser) Update() *TreasuryUserUpdateOne {
	return NewTreasuryUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TreasuryUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TreasuryUser) Unwrap() *TreasuryUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TreasuryUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TreasuryUser) String() string {
	var builder strings.Builder
	builder.WriteString("TreasuryUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("auth_service_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthServiceUserID))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("sync_status=")
	builder.WriteString(_m.SyncStatus)
	builder.WriteString(", ")
	builder.WriteString("last_sync_at=")
	builder.WriteString(_m.LastSyncAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TreasuryUsers is a parsable slice of TreasuryUser.
type TreasuryUsers []*TreasuryUser
