// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/treasury-api/internal/ent/predicate"
	"github.com/bengobox/treasury-api/internal/ent/treasuryrole"
	"github.com/bengobox/treasury-api/internal/ent/treasuryuser"
	"github.com/bengobox/treasury-api/internal/ent/userroleassignment"
	"github.com/google/uuid"
)

// UserRoleAssignmentUpdate is the builder for updating UserRoleAssignment entities.
type UserRoleAssignmentUpdate struct {
	config
	hooks    []Hook
	mutation *UserRoleAssignmentMutation
}

// Where appends a list predicates to the UserRoleAssignmentUpdate builder.
func (_u *UserRoleAssignmentUpdate) Where(ps ...predicate.UserRoleAssignment) *UserRoleAssignmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *UserRoleAssignmentUpdate) SetTenantID(v uuid.UUID) *UserRoleAssignmentUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdate) SetNillableTenantID(v *uuid.UUID) *UserRoleAssignmentUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRoleAssignmentUpdate) SetUserID(v uuid.UUID) *UserRoleAssignmentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdate) SetNillableUserID(v *uuid.UUID) *UserRoleAssignmentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *UserRoleAssignmentUpdate) SetRoleID(v uuid.UUID) *UserRoleAssignmentUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdate) SetNillableRoleID(v *uuid.UUID) *UserRoleAssignmentUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserRoleAssignmentUpdate) SetAssignedBy(v uuid.UUID) *UserRoleAssignmentUpdate {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdate) SetNillableAssignedBy(v *uuid.UUID) *UserRoleAssignmentUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserRoleAssignmentUpdate) SetExpiresAt(v time.Time) *UserRoleAssignmentUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdate) SetNillableExpiresAt(v *time.Time) *UserRoleAssignmentUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserRoleAssignmentUpdate) ClearExpiresAt() *UserRoleAssignmentUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the TreasuryUser entity.
func (_u *UserRoleAssignmentUpdate) SetUser(v *TreasuryUser) *UserRoleAssignmentUpdate {
	return _u.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the TreasuryRole entity.
func (_u *UserRoleAssignmentUpdate) SetRole(v *TreasuryRole) *UserRoleAssignmentUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the UserRoleAssignmentMutation object of the builder.
func (_u *UserRoleAssignmentUpdate) Mutation() *UserRoleAssignmentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the TreasuryUser entity.
func (_u *UserRoleAssignmentUpdate) ClearUser() *UserRoleAssignmentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRole clears the "role" edge to the TreasuryRole entity.
func (_u *UserRoleAssignmentUpdate) ClearRole() *UserRoleAssignmentUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserRoleAssignmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRoleAssignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserRoleAssignmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRoleAssignmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRoleAssignmentUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRoleAssignment.user"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRoleAssignment.role"`)
	}
	return nil
}

func (_u *UserRoleAssignmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userroleassignment.Table, userroleassignment.Columns, sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(userroleassignment.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.AssignedBy(); ok {
		_spec.SetField(userroleassignment.FieldAssignedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userroleassignment.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userroleassignment.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.UserTable,
			Columns: []string{userroleassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryuser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.UserTable,
			Columns: []string{userroleassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.RoleTable,
			Columns: []string{userroleassignment.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.RoleTable,
			Columns: []string{userroleassignment.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userroleassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserRoleAssignmentUpdateOne is the builder for updating a single UserRoleAssignment entity.
type UserRoleAssignmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRoleAssignmentMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *UserRoleAssignmentUpdateOne) SetTenantID(v uuid.UUID) *UserRoleAssignmentUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdateOne) SetNillableTenantID(v *uuid.UUID) *UserRoleAssignmentUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRoleAssignmentUpdateOne) SetUserID(v uuid.UUID) *UserRoleAssignmentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdateOne) SetNillableUserID(v *uuid.UUID) *UserRoleAssignmentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *UserRoleAssignmentUpdateOne) SetRoleID(v uuid.UUID) *UserRoleAssignmentUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdateOne) SetNillableRoleID(v *uuid.UUID) *UserRoleAssignmentUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserRoleAssignmentUpdateOne) SetAssignedBy(v uuid.UUID) *UserRoleAssignmentUpdateOne {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdateOne) SetNillableAssignedBy(v *uuid.UUID) *UserRoleAssignmentUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserRoleAssignmentUpdateOne) SetExpiresAt(v time.Time) *UserRoleAssignmentUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserRoleAssignmentUpdateOne) SetNillableExpiresAt(v *time.Time) *UserRoleAssignmentUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserRoleAssignmentUpdateOne) ClearExpiresAt() *UserRoleAssignmentUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUser sets the "user" edge to the TreasuryUser entity.
func (_u *UserRoleAssignmentUpdateOne) SetUser(v *TreasuryUser) *UserRoleAssignmentUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the TreasuryRole entity.
func (_u *UserRoleAssignmentUpdateOne) SetRole(v *TreasuryRole) *UserRoleAssignmentUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the UserRoleAssignmentMutation object of the builder.
func (_u *UserRoleAssignmentUpdateOne) Mutation() *UserRoleAssignmentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the TreasuryUser entity.
func (_u *UserRoleAssignmentUpdateOne) ClearUser() *UserRoleAssignmentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRole clears the "role" edge to the TreasuryRole entity.
func (_u *UserRoleAssignmentUpdateOne) ClearRole() *UserRoleAssignmentUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the UserRoleAssignmentUpdate builder.
func (_u *UserRoleAssignmentUpdateOne) Where(ps ...predicate.UserRoleAssignment) *UserRoleAssignmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserRoleAssignmentUpdateOne) Select(field string, fields ...string) *UserRoleAssignmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserRoleAssignment entity.
func (_u *UserRoleAssignmentUpdateOne) Save(ctx context.Context) (*UserRoleAssignment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRoleAssignmentUpdateOne) SaveX(ctx context.Context) *UserRoleAssignment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserRoleAssignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRoleAssignmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRoleAssignmentUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRoleAssignment.user"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRoleAssignment.role"`)
	}
	return nil
}

func (_u *UserRoleAssignmentUpdateOne) sqlSave(ctx context.Context) (_node *UserRoleAssignment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userroleassignment.Table, userroleassignment.Columns, sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRoleAssignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userroleassignment.FieldID)
		for _, f := range fields {
			if !userroleassignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userroleassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(userroleassignment.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.AssignedBy(); ok {
		_spec.SetField(userroleassignment.FieldAssignedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userroleassignment.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userroleassignment.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.UserTable,
			Columns: []string{userroleassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryuser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.UserTable,
			Columns: []string{userroleassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.RoleTable,
			Columns: []string{userroleassignment.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.RoleTable,
			Columns: []string{userroleassignment.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRoleAssignment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userroleassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
