// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/treasury-api/internal/ent/treasuryrole"
	"github.com/bengobox/treasury-api/internal/ent/treasuryuser"
	"github.com/bengobox/treasury-api/internal/ent/userroleassignment"
	"github.com/google/uuid"
)

// UserRoleAssignmentCreate is the builder for creating a UserRoleAssignment entity.
type UserRoleAssignmentCreate struct {
	config
	mutation *UserRoleAssignmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *UserRoleAssignmentCreate) SetTenantID(v uuid.UUID) *UserRoleAssignmentCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserRoleAssignmentCreate) SetUserID(v uuid.UUID) *UserRoleAssignmentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *UserRoleAssignmentCreate) SetRoleID(v uuid.UUID) *UserRoleAssignmentCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *UserRoleAssignmentCreate) SetAssignedBy(v uuid.UUID) *UserRoleAssignmentCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *UserRoleAssignmentCreate) SetAssignedAt(v time.Time) *UserRoleAssignmentCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *UserRoleAssignmentCreate) SetNillableAssignedAt(v *time.Time) *UserRoleAssignmentCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserRoleAssignmentCreate) SetExpiresAt(v time.Time) *UserRoleAssignmentCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UserRoleAssignmentCreate) SetNillableExpiresAt(v *time.Time) *UserRoleAssignmentCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserRoleAssignmentCreate) SetID(v uuid.UUID) *UserRoleAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserRoleAssignmentCreate) SetNillableID(v *uuid.UUID) *UserRoleAssignmentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the TreasuryUser entity.
func (_c *UserRoleAssignmentCreate) SetUser(v *TreasuryUser) *UserRoleAssignmentCreate {
	return _c.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the TreasuryRole entity.
func (_c *UserRoleAssignmentCreate) SetRole(v *TreasuryRole) *UserRoleAssignmentCreate {
	return _c.SetRoleID(v.ID)
}

// Mutation returns the UserRoleAssignmentMutation object of the builder.
func (_c *UserRoleAssignmentCreate) Mutation() *UserRoleAssignmentMutation {
	return _c.mutation
}

// Save creates the UserRoleAssignment in the database.
func (_c *UserRoleAssignmentCreate) Save(ctx context.Context) (*UserRoleAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserRoleAssignmentCreate) SaveX(ctx context.Context) *UserRoleAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRoleAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRoleAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserRoleAssignmentCreate) defaults() {
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := userroleassignment.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userroleassignment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserRoleAssignmentCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "UserRoleAssignment.tenant_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserRoleAssignment.user_id"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "UserRoleAssignment.role_id"`)}
	}
	if _, ok := _c.mutation.AssignedBy(); !ok {
		return &ValidationError{Name: "assigned_by", err: errors.New(`ent: missing required field "UserRoleAssignment.assigned_by"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "UserRoleAssignment.assigned_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserRoleAssignment.user"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "UserRoleAssignment.role"`)}
	}
	return nil
}

func (_c *UserRoleAssignmentCreate) sqlSave(ctx context.Context) (*UserRoleAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserRoleAssignmentCreate) createSpec() (*UserRoleAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &UserRoleAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userroleassignment.Table, sqlgraph.NewFieldSpec(userroleassignment.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(userroleassignment.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.AssignedBy(); ok {
		_spec.SetField(userroleassignment.FieldAssignedBy, field.TypeUUID, value)
		_node.AssignedBy = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(userroleassignment.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userroleassignment.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.UserTable,
			Columns: []string{userroleassignment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userroleassignment.RoleTable,
			Columns: []string{userroleassignment.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(treasuryrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRoleAssignment.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRoleAssignmentUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRoleAssignmentCreate) OnConflict(opts ...sql.ConflictOption) *UserRoleAssignmentUpsertOne {
	_c.conflict = opts
	return &UserRoleAssignmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRoleAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRoleAssignmentCreate) OnConflictColumns(columns ...string) *UserRoleAssignmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRoleAssignmentUpsertOne{
		create: _c,
	}
}

type (
	// UserRoleAssignmentUpsertOne is the builder for "upsert"-ing
	//  one UserRoleAssignment node.
	UserRoleAssignmentUpsertOne struct {
		create *UserRoleAssignmentCreate
	}

	// UserRoleAssignmentUpsert is the "OnConflict" setter.
	UserRoleAssignmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *UserRoleAssignmentUpsert) SetTenantID(v uuid.UUID) *UserRoleAssignmentUpsert {
	u.Set(userroleassignment.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsert) UpdateTenantID() *UserRoleAssignmentUpsert {
	u.SetExcluded(userroleassignment.FieldTenantID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRoleAssignmentUpsert) SetUserID(v uuid.UUID) *UserRoleAssignmentUpsert {
	u.Set(userroleassignment.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsert) UpdateUserID() *UserRoleAssignmentUpsert {
	u.SetExcluded(userroleassignment.FieldUserID)
	return u
}

// SetRoleID sets the "role_id" field.
func (u *UserRoleAssignmentUpsert) SetRoleID(v uuid.UUID) *UserRoleAssignmentUpsert {
	u.Set(userroleassignment.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsert) UpdateRoleID() *UserRoleAssignmentUpsert {
	u.SetExcluded(userroleassignment.FieldRoleID)
	return u
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserRoleAssignmentUpsert) SetAssignedBy(v uuid.UUID) *UserRoleAssignmentUpsert {
	u.Set(userroleassignment.FieldAssignedBy, v)
	return u
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsert) UpdateAssignedBy() *UserRoleAssignmentUpsert {
	u.SetExcluded(userroleassignment.FieldAssignedBy)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserRoleAssignmentUpsert) SetExpiresAt(v time.Time) *UserRoleAssignmentUpsert {
	u.Set(userroleassignment.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsert) UpdateExpiresAt() *UserRoleAssignmentUpsert {
	u.SetExcluded(userroleassignment.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserRoleAssignmentUpsert) ClearExpiresAt() *UserRoleAssignmentUpsert {
	u.SetNull(userroleassignment.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserRoleAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userroleassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserRoleAssignmentUpsertOne) UpdateNewValues() *UserRoleAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(userroleassignment.FieldID)
		}
		if _, exists := u.create.mutation.AssignedAt(); exists {
			s.SetIgnore(userroleassignment.FieldAssignedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRoleAssignment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserRoleAssignmentUpsertOne) Ignore() *UserRoleAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRoleAssignmentUpsertOne) DoNothing() *UserRoleAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRoleAssignmentCreate.OnConflict
// documentation for more info.
func (u *UserRoleAssignmentUpsertOne) Update(set func(*UserRoleAssignmentUpsert)) *UserRoleAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRoleAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *UserRoleAssignmentUpsertOne) SetTenantID(v uuid.UUID) *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertOne) UpdateTenantID() *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateTenantID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserRoleAssignmentUpsertOne) SetUserID(v uuid.UUID) *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertOne) UpdateUserID() *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateUserID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *UserRoleAssignmentUpsertOne) SetRoleID(v uuid.UUID) *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertOne) UpdateRoleID() *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateRoleID()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserRoleAssignmentUpsertOne) SetAssignedBy(v uuid.UUID) *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertOne) UpdateAssignedBy() *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateAssignedBy()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserRoleAssignmentUpsertOne) SetExpiresAt(v time.Time) *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertOne) UpdateExpiresAt() *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserRoleAssignmentUpsertOne) ClearExpiresAt() *UserRoleAssignmentUpsertOne {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *UserRoleAssignmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRoleAssignmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRoleAssignmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserRoleAssignmentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UserRoleAssignmentUpsertOne.ID is not supported by MySQL driver. Use UserRoleAssignmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserRoleAssignmentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserRoleAssignmentCreateBulk is the builder for creating many UserRoleAssignment entities in bulk.
type UserRoleAssignmentCreateBulk struct {
	config
	err      error
	builders []*UserRoleAssignmentCreate
	conflict []sql.ConflictOption
}

// Save creates the UserRoleAssignment entities in the database.
func (_c *UserRoleAssignmentCreateBulk) Save(ctx context.Context) ([]*UserRoleAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserRoleAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserRoleAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserRoleAssignmentCreateBulk) SaveX(ctx context.Context) []*UserRoleAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRoleAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRoleAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRoleAssignment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRoleAssignmentUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRoleAssignmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserRoleAssignmentUpsertBulk {
	_c.conflict = opts
	return &UserRoleAssignmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRoleAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRoleAssignmentCreateBulk) OnConflictColumns(columns ...string) *UserRoleAssignmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRoleAssignmentUpsertBulk{
		create: _c,
	}
}

// UserRoleAssignmentUpsertBulk is the builder for "upsert"-ing
// a bulk of UserRoleAssignment nodes.
type UserRoleAssignmentUpsertBulk struct {
	create *UserRoleAssignmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserRoleAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(userroleassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserRoleAssignmentUpsertBulk) UpdateNewValues() *UserRoleAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(userroleassignment.FieldID)
			}
			if _, exists := b.mutation.AssignedAt(); exists {
				s.SetIgnore(userroleassignment.FieldAssignedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRoleAssignment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserRoleAssignmentUpsertBulk) Ignore() *UserRoleAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRoleAssignmentUpsertBulk) DoNothing() *UserRoleAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRoleAssignmentCreateBulk.OnConflict
// documentation for more info.
func (u *UserRoleAssignmentUpsertBulk) Update(set func(*UserRoleAssignmentUpsert)) *UserRoleAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRoleAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *UserRoleAssignmentUpsertBulk) SetTenantID(v uuid.UUID) *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertBulk) UpdateTenantID() *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateTenantID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserRoleAssignmentUpsertBulk) SetUserID(v uuid.UUID) *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertBulk) UpdateUserID() *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateUserID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *UserRoleAssignmentUpsertBulk) SetRoleID(v uuid.UUID) *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertBulk) UpdateRoleID() *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateRoleID()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserRoleAssignmentUpsertBulk) SetAssignedBy(v uuid.UUID) *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertBulk) UpdateAssignedBy() *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateAssignedBy()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserRoleAssignmentUpsertBulk) SetExpiresAt(v time.Time) *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserRoleAssignmentUpsertBulk) UpdateExpiresAt() *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserRoleAssignmentUpsertBulk) ClearExpiresAt() *UserRoleAssignmentUpsertBulk {
	return u.Update(func(s *UserRoleAssignmentUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *UserRoleAssignmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserRoleAssignmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRoleAssignmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRoleAssignmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
