// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChartOfAccount is the predicate function for chartofaccount builders.
type ChartOfAccount func(*sql.Selector)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// LedgerTransaction is the predicate function for ledgertransaction builders.
type LedgerTransaction func(*sql.Selector)

// OutboxEvent is the predicate function for outboxevent builders.
type OutboxEvent func(*sql.Selector)

// PaymentIntent is the predicate function for paymentintent builders.
type PaymentIntent func(*sql.Selector)

// PaymentTransaction is the predicate function for paymenttransaction builders.
type PaymentTransaction func(*sql.Selector)

// RolePermission is the predicate function for rolepermission builders.
type RolePermission func(*sql.Selector)

// TreasuryPermission is the predicate function for treasurypermission builders.
type TreasuryPermission func(*sql.Selector)

// TreasuryRole is the predicate function for treasuryrole builders.
type TreasuryRole func(*sql.Selector)

// TreasuryUser is the predicate function for treasuryuser builders.
type TreasuryUser func(*sql.Selector)

// UserRoleAssignment is the predicate function for userroleassignment builders.
type UserRoleAssignment func(*sql.Selector)
