// Code generated by ent, DO NOT EDIT.

package userroleassignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/treasury-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldTenantID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldUserID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldRoleID, v))
}

// AssignedBy applies equality check predicate on the "assigned_by" field. It's identical to AssignedByEQ.
func AssignedBy(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldAssignedBy, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldAssignedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldExpiresAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLTE(FieldTenantID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNotIn(FieldUserID, vs...))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNotIn(FieldRoleID, vs...))
}

// AssignedByEQ applies the EQ predicate on the "assigned_by" field.
func AssignedByEQ(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldAssignedBy, v))
}

// AssignedByNEQ applies the NEQ predicate on the "assigned_by" field.
func AssignedByNEQ(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNEQ(FieldAssignedBy, v))
}

// AssignedByIn applies the In predicate on the "assigned_by" field.
func AssignedByIn(vs ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldIn(FieldAssignedBy, vs...))
}

// AssignedByNotIn applies the NotIn predicate on the "assigned_by" field.
func AssignedByNotIn(vs ...uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNotIn(FieldAssignedBy, vs...))
}

// AssignedByGT applies the GT predicate on the "assigned_by" field.
func AssignedByGT(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGT(FieldAssignedBy, v))
}

// AssignedByGTE applies the GTE predicate on the "assigned_by" field.
func AssignedByGTE(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGTE(FieldAssignedBy, v))
}

// AssignedByLT applies the LT predicate on the "assigned_by" field.
func AssignedByLT(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLT(FieldAssignedBy, v))
}

// AssignedByLTE applies the LTE predicate on the "assigned_by" field.
func AssignedByLTE(v uuid.UUID) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLTE(FieldAssignedBy, v))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLTE(FieldAssignedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.FieldNotNull(FieldExpiresAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.TreasuryUser) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.TreasuryRole) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserRoleAssignment) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserRoleAssignment) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserRoleAssignment) predicate.UserRoleAssignment {
	return predicate.UserRoleAssignment(sql.NotPredicates(p))
}
