// Code generated by ent, DO NOT EDIT.

package ledgertransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/treasury-api/internal/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldTenantID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldAccountID, v))
}

// JournalEntryID applies equality check predicate on the "journal_entry_id" field. It's identical to JournalEntryIDEQ.
func JournalEntryID(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldJournalEntryID, v))
}

// DebitAmount applies equality check predicate on the "debit_amount" field. It's identical to DebitAmountEQ.
func DebitAmount(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldDebitAmount, v))
}

// CreditAmount applies equality check predicate on the "credit_amount" field. It's identical to CreditAmountEQ.
func CreditAmount(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldCreditAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldCurrency, v))
}

// ExchangeRate applies equality check predicate on the "exchange_rate" field. It's identical to ExchangeRateEQ.
func ExchangeRate(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldExchangeRate, v))
}

// ReferenceType applies equality check predicate on the "reference_type" field. It's identical to ReferenceTypeEQ.
func ReferenceType(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceID applies equality check predicate on the "reference_id" field. It's identical to ReferenceIDEQ.
func ReferenceID(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldReferenceID, v))
}

// TransactionDate applies equality check predicate on the "transaction_date" field. It's identical to TransactionDateEQ.
func TransactionDate(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldTransactionDate, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldTenantID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldAccountID, vs...))
}

// JournalEntryIDEQ applies the EQ predicate on the "journal_entry_id" field.
func JournalEntryIDEQ(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldJournalEntryID, v))
}

// JournalEntryIDNEQ applies the NEQ predicate on the "journal_entry_id" field.
func JournalEntryIDNEQ(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldJournalEntryID, v))
}

// JournalEntryIDIn applies the In predicate on the "journal_entry_id" field.
func JournalEntryIDIn(vs ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldJournalEntryID, vs...))
}

// JournalEntryIDNotIn applies the NotIn predicate on the "journal_entry_id" field.
func JournalEntryIDNotIn(vs ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldJournalEntryID, vs...))
}

// JournalEntryIDGT applies the GT predicate on the "journal_entry_id" field.
func JournalEntryIDGT(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldJournalEntryID, v))
}

// JournalEntryIDGTE applies the GTE predicate on the "journal_entry_id" field.
func JournalEntryIDGTE(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldJournalEntryID, v))
}

// JournalEntryIDLT applies the LT predicate on the "journal_entry_id" field.
func JournalEntryIDLT(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldJournalEntryID, v))
}

// JournalEntryIDLTE applies the LTE predicate on the "journal_entry_id" field.
func JournalEntryIDLTE(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldJournalEntryID, v))
}

// JournalEntryIDIsNil applies the IsNil predicate on the "journal_entry_id" field.
func JournalEntryIDIsNil() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIsNull(FieldJournalEntryID))
}

// JournalEntryIDNotNil applies the NotNil predicate on the "journal_entry_id" field.
func JournalEntryIDNotNil() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotNull(FieldJournalEntryID))
}

// DebitAmountEQ applies the EQ predicate on the "debit_amount" field.
func DebitAmountEQ(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldDebitAmount, v))
}

// DebitAmountNEQ applies the NEQ predicate on the "debit_amount" field.
func DebitAmountNEQ(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldDebitAmount, v))
}

// DebitAmountIn applies the In predicate on the "debit_amount" field.
func DebitAmountIn(vs ...decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldDebitAmount, vs...))
}

// DebitAmountNotIn applies the NotIn predicate on the "debit_amount" field.
func DebitAmountNotIn(vs ...decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldDebitAmount, vs...))
}

// DebitAmountGT applies the GT predicate on the "debit_amount" field.
func DebitAmountGT(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldDebitAmount, v))
}

// DebitAmountGTE applies the GTE predicate on the "debit_amount" field.
func DebitAmountGTE(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldDebitAmount, v))
}

// DebitAmountLT applies the LT predicate on the "debit_amount" field.
func DebitAmountLT(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldDebitAmount, v))
}

// DebitAmountLTE applies the LTE predicate on the "debit_amount" field.
func DebitAmountLTE(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldDebitAmount, v))
}

// CreditAmountEQ applies the EQ predicate on the "credit_amount" field.
func CreditAmountEQ(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldCreditAmount, v))
}

// CreditAmountNEQ applies the NEQ predicate on the "credit_amount" field.
func CreditAmountNEQ(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldCreditAmount, v))
}

// CreditAmountIn applies the In predicate on the "credit_amount" field.
func CreditAmountIn(vs ...decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldCreditAmount, vs...))
}

// CreditAmountNotIn applies the NotIn predicate on the "credit_amount" field.
func CreditAmountNotIn(vs ...decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldCreditAmount, vs...))
}

// CreditAmountGT applies the GT predicate on the "credit_amount" field.
func CreditAmountGT(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldCreditAmount, v))
}

// CreditAmountGTE applies the GTE predicate on the "credit_amount" field.
func CreditAmountGTE(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldCreditAmount, v))
}

// CreditAmountLT applies the LT predicate on the "credit_amount" field.
func CreditAmountLT(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldCreditAmount, v))
}

// CreditAmountLTE applies the LTE predicate on the "credit_amount" field.
func CreditAmountLTE(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldCreditAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldContainsFold(FieldCurrency, v))
}

// ExchangeRateEQ applies the EQ predicate on the "exchange_rate" field.
func ExchangeRateEQ(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldExchangeRate, v))
}

// ExchangeRateNEQ applies the NEQ predicate on the "exchange_rate" field.
func ExchangeRateNEQ(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldExchangeRate, v))
}

// ExchangeRateIn applies the In predicate on the "exchange_rate" field.
func ExchangeRateIn(vs ...decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldExchangeRate, vs...))
}

// ExchangeRateNotIn applies the NotIn predicate on the "exchange_rate" field.
func ExchangeRateNotIn(vs ...decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldExchangeRate, vs...))
}

// ExchangeRateGT applies the GT predicate on the "exchange_rate" field.
func ExchangeRateGT(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldExchangeRate, v))
}

// ExchangeRateGTE applies the GTE predicate on the "exchange_rate" field.
func ExchangeRateGTE(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldExchangeRate, v))
}

// ExchangeRateLT applies the LT predicate on the "exchange_rate" field.
func ExchangeRateLT(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldExchangeRate, v))
}

// ExchangeRateLTE applies the LTE predicate on the "exchange_rate" field.
func ExchangeRateLTE(v decimal.Decimal) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldExchangeRate, v))
}

// ReferenceTypeEQ applies the EQ predicate on the "reference_type" field.
func ReferenceTypeEQ(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceTypeNEQ applies the NEQ predicate on the "reference_type" field.
func ReferenceTypeNEQ(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldReferenceType, v))
}

// ReferenceTypeIn applies the In predicate on the "reference_type" field.
func ReferenceTypeIn(vs ...string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldReferenceType, vs...))
}

// ReferenceTypeNotIn applies the NotIn predicate on the "reference_type" field.
func ReferenceTypeNotIn(vs ...string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldReferenceType, vs...))
}

// ReferenceTypeGT applies the GT predicate on the "reference_type" field.
func ReferenceTypeGT(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldReferenceType, v))
}

// ReferenceTypeGTE applies the GTE predicate on the "reference_type" field.
func ReferenceTypeGTE(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldReferenceType, v))
}

// ReferenceTypeLT applies the LT predicate on the "reference_type" field.
func ReferenceTypeLT(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldReferenceType, v))
}

// ReferenceTypeLTE applies the LTE predicate on the "reference_type" field.
func ReferenceTypeLTE(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldReferenceType, v))
}

// ReferenceTypeContains applies the Contains predicate on the "reference_type" field.
func ReferenceTypeContains(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldContains(FieldReferenceType, v))
}

// ReferenceTypeHasPrefix applies the HasPrefix predicate on the "reference_type" field.
func ReferenceTypeHasPrefix(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldHasPrefix(FieldReferenceType, v))
}

// ReferenceTypeHasSuffix applies the HasSuffix predicate on the "reference_type" field.
func ReferenceTypeHasSuffix(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldHasSuffix(FieldReferenceType, v))
}

// ReferenceTypeIsNil applies the IsNil predicate on the "reference_type" field.
func ReferenceTypeIsNil() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIsNull(FieldReferenceType))
}

// ReferenceTypeNotNil applies the NotNil predicate on the "reference_type" field.
func ReferenceTypeNotNil() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotNull(FieldReferenceType))
}

// ReferenceTypeEqualFold applies the EqualFold predicate on the "reference_type" field.
func ReferenceTypeEqualFold(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEqualFold(FieldReferenceType, v))
}

// ReferenceTypeContainsFold applies the ContainsFold predicate on the "reference_type" field.
func ReferenceTypeContainsFold(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldContainsFold(FieldReferenceType, v))
}

// ReferenceIDEQ applies the EQ predicate on the "reference_id" field.
func ReferenceIDEQ(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldReferenceID, v))
}

// ReferenceIDNEQ applies the NEQ predicate on the "reference_id" field.
func ReferenceIDNEQ(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldReferenceID, v))
}

// ReferenceIDIn applies the In predicate on the "reference_id" field.
func ReferenceIDIn(vs ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldReferenceID, vs...))
}

// ReferenceIDNotIn applies the NotIn predicate on the "reference_id" field.
func ReferenceIDNotIn(vs ...uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldReferenceID, vs...))
}

// ReferenceIDGT applies the GT predicate on the "reference_id" field.
func ReferenceIDGT(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldReferenceID, v))
}

// ReferenceIDGTE applies the GTE predicate on the "reference_id" field.
func ReferenceIDGTE(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldReferenceID, v))
}

// ReferenceIDLT applies the LT predicate on the "reference_id" field.
func ReferenceIDLT(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldReferenceID, v))
}

// ReferenceIDLTE applies the LTE predicate on the "reference_id" field.
func ReferenceIDLTE(v uuid.UUID) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldReferenceID, v))
}

// ReferenceIDIsNil applies the IsNil predicate on the "reference_id" field.
func ReferenceIDIsNil() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIsNull(FieldReferenceID))
}

// ReferenceIDNotNil applies the NotNil predicate on the "reference_id" field.
func ReferenceIDNotNil() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotNull(FieldReferenceID))
}

// TransactionDateEQ applies the EQ predicate on the "transaction_date" field.
func TransactionDateEQ(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldTransactionDate, v))
}

// TransactionDateNEQ applies the NEQ predicate on the "transaction_date" field.
func TransactionDateNEQ(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldTransactionDate, v))
}

// TransactionDateIn applies the In predicate on the "transaction_date" field.
func TransactionDateIn(vs ...time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldTransactionDate, vs...))
}

// TransactionDateNotIn applies the NotIn predicate on the "transaction_date" field.
func TransactionDateNotIn(vs ...time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldTransactionDate, vs...))
}

// TransactionDateGT applies the GT predicate on the "transaction_date" field.
func TransactionDateGT(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldTransactionDate, v))
}

// TransactionDateGTE applies the GTE predicate on the "transaction_date" field.
func TransactionDateGTE(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldTransactionDate, v))
}

// TransactionDateLT applies the LT predicate on the "transaction_date" field.
func TransactionDateLT(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldTransactionDate, v))
}

// TransactionDateLTE applies the LTE predicate on the "transaction_date" field.
func TransactionDateLTE(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldTransactionDate, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.LedgerTransaction {
	return predicate.LedgerTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.ChartOfAccount) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LedgerTransaction) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LedgerTransaction) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LedgerTransaction) predicate.LedgerTransaction {
	return predicate.LedgerTransaction(sql.NotPredicates(p))
}
