// Code generated by ent, DO NOT EDIT.

package treasuryrole

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/treasury-api/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldTenantID, v))
}

// RoleCode applies equality check predicate on the "role_code" field. It's identical to RoleCodeEQ.
func RoleCode(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldRoleCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldDescription, v))
}

// IsSystemRole applies equality check predicate on the "is_system_role" field. It's identical to IsSystemRoleEQ.
func IsSystemRole(v bool) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldIsSystemRole, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLTE(FieldTenantID, v))
}

// RoleCodeEQ applies the EQ predicate on the "role_code" field.
func RoleCodeEQ(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldRoleCode, v))
}

// RoleCodeNEQ applies the NEQ predicate on the "role_code" field.
func RoleCodeNEQ(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNEQ(FieldRoleCode, v))
}

// RoleCodeIn applies the In predicate on the "role_code" field.
func RoleCodeIn(vs ...string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldIn(FieldRoleCode, vs...))
}

// RoleCodeNotIn applies the NotIn predicate on the "role_code" field.
func RoleCodeNotIn(vs ...string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNotIn(FieldRoleCode, vs...))
}

// RoleCodeGT applies the GT predicate on the "role_code" field.
func RoleCodeGT(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGT(FieldRoleCode, v))
}

// RoleCodeGTE applies the GTE predicate on the "role_code" field.
func RoleCodeGTE(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGTE(FieldRoleCode, v))
}

// RoleCodeLT applies the LT predicate on the "role_code" field.
func RoleCodeLT(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLT(FieldRoleCode, v))
}

// RoleCodeLTE applies the LTE predicate on the "role_code" field.
func RoleCodeLTE(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLTE(FieldRoleCode, v))
}

// RoleCodeContains applies the Contains predicate on the "role_code" field.
func RoleCodeContains(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldContains(FieldRoleCode, v))
}

// RoleCodeHasPrefix applies the HasPrefix predicate on the "role_code" field.
func RoleCodeHasPrefix(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldHasPrefix(FieldRoleCode, v))
}

// RoleCodeHasSuffix applies the HasSuffix predicate on the "role_code" field.
func RoleCodeHasSuffix(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldHasSuffix(FieldRoleCode, v))
}

// RoleCodeEqualFold applies the EqualFold predicate on the "role_code" field.
func RoleCodeEqualFold(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEqualFold(FieldRoleCode, v))
}

// RoleCodeContainsFold applies the ContainsFold predicate on the "role_code" field.
func RoleCodeContainsFold(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldContainsFold(FieldRoleCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldContainsFold(FieldDescription, v))
}

// IsSystemRoleEQ applies the EQ predicate on the "is_system_role" field.
func IsSystemRoleEQ(v bool) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldIsSystemRole, v))
}

// IsSystemRoleNEQ applies the NEQ predicate on the "is_system_role" field.
func IsSystemRoleNEQ(v bool) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNEQ(FieldIsSystemRole, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPermissions applies the HasEdge predicate on the "permissions" edge.
func HasPermissions() predicate.TreasuryRole {
	return predicate.TreasuryRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, PermissionsTable, PermissionsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPermissionsWith applies the HasEdge predicate on the "permissions" edge with a given conditions (other predicates).
func HasPermissionsWith(preds ...predicate.TreasuryPermission) predicate.TreasuryRole {
	return predicate.TreasuryRole(func(s *sql.Selector) {
		step := newPermissionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserAssignments applies the HasEdge predicate on the "user_assignments" edge.
func HasUserAssignments() predicate.TreasuryRole {
	return predicate.TreasuryRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserAssignmentsTable, UserAssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserAssignmentsWith applies the HasEdge predicate on the "user_assignments" edge with a given conditions (other predicates).
func HasUserAssignmentsWith(preds ...predicate.UserRoleAssignment) predicate.TreasuryRole {
	return predicate.TreasuryRole(func(s *sql.Selector) {
		step := newUserAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRolePermissions applies the HasEdge predicate on the "role_permissions" edge.
func HasRolePermissions() predicate.TreasuryRole {
	return predicate.TreasuryRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RolePermissionsTable, RolePermissionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRolePermissionsWith applies the HasEdge predicate on the "role_permissions" edge with a given conditions (other predicates).
func HasRolePermissionsWith(preds ...predicate.RolePermission) predicate.TreasuryRole {
	return predicate.TreasuryRole(func(s *sql.Selector) {
		step := newRolePermissionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TreasuryRole) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TreasuryRole) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TreasuryRole) predicate.TreasuryRole {
	return predicate.TreasuryRole(sql.NotPredicates(p))
}
